### ISSUE TITLE
UnsatisfiedLinkError for dgemm_offsets

### ISSUE THREAD

**Issue by jmelot** [scalanlp/breeze#142]
Hello,

(I just posted this to netlib-java as an issue; reposting it here in case this is actually a breeze issue. Thanks!)

I'm running netlib-java through breeze. I specify this parameter:

-Dcom.github.fommil.netlib.NativeSystemBLAS.natives=my_blas_shared_object.so

where "my_blas_shared_object.so" is either the libblas.so that was already installed on my computer (in /usr/lib/libblas.so), or the one I get when I build OpenBLAS.

When I then do a matrix x matrix multiply between two Breeze DenseMatrixes, I get the following error:

Jan 30, 2014 11:14:00 AM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded /home/jmelot/breeze-fwd-pass/OpenBLAS-master/libopenblasp-r0.2.8.so
java.lang.UnsatisfiedLinkError: com.github.fommil.netlib.NativeSystemBLAS.dgemm_offsets(Ljava/lang/String;Ljava/lang/String;IIID[DII[DIID[DII)V

If I do not specify com.github.fommil.netlib.NativeSystemBLAS.natives, netlib-java falls back to the reference blas implementation.

What I am running:

Ubuntu: Ubuntu 12.04.4 LTS x86_64
Java: 1.6.0_27
Breeze: 0.6-SNAPSHOT
Netlib: 1.1
OpenBLAS: 0.2.8 (latest release) and 0.2.9 (head in the develop branch)

I get this error when I build OpenBLAS with or without the parameters "NO_LAPACK=0" and "NO_CBLAS=0". 

Do you know what could be the problem? Thanks!

**Comment by jbesa** [comment]
@jmelot How did you compile the JNI bindings? I'm having a lot of trouble in Centos 6.5. I tried to compile them but is not working at all. Thank you very much.
