### ISSUE TITLE
Implement the L-BFGS-B algorithm

### ISSUE THREAD

**Issue by tartakynov** [scalanlp/breeze#323]
In a real-world when you are solving an optimization problem it is often required to specify a bound constrains on variables, so it would be nice to implement L-BFGS-B algorithm, i.e. extend L-BFGS to handle simple box constrains on variables

**Comment by dlwh** [comment]
If anyone wants to implement this: https://github.com/PatWie/CppNumericalSolvers/blob/master/src/LbfgsbSolver.cpp

**Comment by dreamquster** [comment]
I implement this method.But I have some question?
1. If StrongWolfeLineSearch(maxZoomIter,maxLineSearchIter) is small, the wolfeRuleSearch.minimize may throw FirstOrderException.That's why?
2.In FirstOrderMinimizer.State.convergedReason
   if (!fVals.isEmpty && (adjustedValue - fVals.max).abs <= tolerance * initialAdjVal)
        Some(FirstOrderMinimizer.FunctionValuesConverged)
   If init x made initialAdjVal is bigger enough, the FirstOrderMinimizer may exit quickly without reaching minimal value?
3. What's wrong with this code style?
    when x and dirk is DenseVector[Double]
    x = x + dirk:*2  is not equal to x += dirk:*2

**Comment by dlwh** [comment]
First, thanks so much for taking this on!

I'm not sure I totally understand all your questions.

On Wed, Mar 25, 2015 at 12:38 AM, dreamquster <notifications@github.com>
wrote:

> I implement this method.But I have some question?
> 1. If StrongWolfeLineSearch(maxZoomIter,maxLineSearchIter) is small, the
> wolfeRuleSearch.minimize may throw FirstOrderException.That's why?
> 2.In FirstOrderMinimizer.State.convergedReason
> if (!fVals.isEmpty && (adjustedValue - fVals.max).abs <= tolerance *
> initialAdjVal)
> Some(FirstOrderMinimizer.FunctionValuesConverged)
> If init x made initialAdjVal is bigger enough, the FirstOrderMinimizer may
> exit quickly without reaching minimal value?
>
Yeah, we're working on changing the convergence criteria.


> 3. What's wrong with this code style?
> when x and dirk is DenseVector[Double]
> x = x + dirk:*2 is not equal to x += dirk:*2
>

Those ought to be the same? Can you give an example?

**Comment by dlwh** [comment]
Hit send too soon:

On Wed, Mar 25, 2015 at 12:38 AM, dreamquster <notifications@github.com>
 wrote:

> I implement this method.But I have some question?
> 1. If StrongWolfeLineSearch(maxZoomIter,maxLineSearchIter) is small, the
> wolfeRuleSearch.minimize may throw FirstOrderException.That's why?
>
I don't understand what you mean here? If it can't find stepsize that
satisfies the wolfe conditions, it will throw.

**Comment by dreamquster** [comment]
The following code failed.
     object VectorTest {

         def main(args:Array[String]) = {
          var x = DenseVector[Double](2.0, 3.0)
          var xcopy = x.copy
          val dir = DenseVector[Double](1.0, 0.0)
          x = x + dir:*0.5
          xcopy += dir:*0.5
          assert(x == xcopy)
        }
    }

**Comment by dreamquster** [comment]
The following code failed.
```
object VectorTest {
  def main(args:Array[String]) = {
    var x = DenseVector[Double](2.0, 3.0)
    var xcopy = x.copy
    val dir = DenseVector[Double](1.0, 0.0)
    x = x + dir:*0.5
    xcopy += dir:*0.5
    assert(x == xcopy)
  }
}
```

**Comment by dlwh** [comment]
ah right, you're getting bitten by operator precedence. operators starting
with : have low priority in Scala. Not much I can do about it, besides pick
a different operator. You can just use * for multiplication by scalars.

**Comment by dreamquster** [comment]
Ok, thanks.

**Comment by dreamquster** [comment]
How to create a new pull request? Why this changed is merged into "numpy parity: financial functions #128" pull?

**Comment by dlwh** [comment]
pull requests are by branch, so every time you push to a branch, the PR
gets updated.

**Comment by dlwh** [comment]
(Thanks @dreamquster ! Cleaned up the implementation to be a bit more pure and added a test. Seems to work great!)
