### ISSUE TITLE
iterable way of defining reduction UFuncs

### ISSUE THREAD

**Issue by antonkulaga** [scalanlp/breeze#331]
It will be great to have an alternative way of defining reduction ufuncs, with Iterable instead of CanTraverse. Issue is based on ( https://groups.google.com/forum/#!topic/scala-breeze/mUkfpilkNq8 )

**Comment by dlwh** [comment]
done. There's now a fold method on CanTraverseValues

**Comment by antonkulaga** [comment]
Great!
