### ISSUE TITLE
why use ARPACK for SVD?

### ISSUE THREAD

**Issue by fommil** [scalanlp/breeze#332]
I was looking through the SVD code and I seen this:

https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/functions/svd.scala#L164

you're using ARPACK to compute the SVD for sparse matrices.

I think this is derived from my MTJ code where we solve the eigensystem with ARPACK

 https://github.com/fommil/matrix-toolkits-java/blob/master/src/main/java/no/uib/cipr/matrix/sparse/ArpackSym.java

but I'm not entirely sure this gives the singular values... has somebody checked the algebra of this and confirmed that it works?

**Comment by dlwh** [comment]
(closing this. we use lapack for dense SVD. Arpack for thin-SVD. I think this is how it should be?)
