### ISSUE TITLE
breeze.optimize.FirstOrderMinimizer convergence conditions

### ISSUE THREAD

**Issue by eidonfiloi** [scalanlp/breeze#338]
Hi,

I had some problems with converging of the optimizer, so I looked at the FirstOrderMinimizer and I found some differences compared to other frameworks' implementations. Specifically: 
For the gradient there is the condition:
 
    else if (norm(adjustedGradient) <= math.max(tolerance * adjustedValue.abs, 1E-8))
            Some(FirstOrderMinimizer.GradientConverged)

I was wondering if instead of math.max one should take math.min? 
Also i was wondering why the adjustedValue.abs is used with respect to the norm of the gradient? Would it be better to take the initial value of the gradient or better the maximum projection of the gradient (e.g. the biggest component of the gradient) and it should be smaller than a tolerance value (without using any initial value)? 

In the same vein, one could use solely a convergence tolerance value for the value condition as well (instead of multiplying it with the initialValue), couldn't one? (as if the function takes big values, then one should choose smaller convergence tolerance, if one wants to avoid fast "convergence" due to improvementFailureError, but then the gradient condition will be never satisfied because of the math.max part.)

Any explanation on the convergence conditions are much appreciated...

**Comment by dlwh** [comment]
I just chose things that seemed reasonable to me. I've never been all that happy with the convergence criteria. Happy to take suggestions/PRs.

But... I don't understand why it should be min? You want something that is (mostly) scale invariant, so you want to use a tolerance relative to something, and the obj value seemed like a good choice of scale? The floor of 1E-8 is just for dealing with objective values that are near zero. Why is the max norm better than the 2 norm?

**Comment by eidonfiloi** [comment]
Thank you for the reply and the clarification of the rationale behind the conditions. My problem is, that I have a function from the exponential family and I want to optimize a log likelihood function with 100k variables. So little changes in the loss function can mean a lot of improvements in the prediction. Thus I do not want to depend on the objective value, I want to have a convergence w.r.t an absolute small tolerance value. So If I want to use the current implementation, I have to choose a very small tolerance (my function takes big values) but then the same tolerance is used in the gradient condition, where because of the max I will finish the convergence way before it actually converges. As a matter of fact, I will stop the optimization because of the improvementFailure parameter set to 0.001. Maybe the tolerance should be used there as well (like in the SciPy implementation of the LBFGS)?. Also SciPy uses the max norm for the gradient, which is maybe much more robust and independent of the number of features etc. (anyway the Lp norms converge to the max norm...)  

Also the line search algorithm uses 0.001 and 0.9 as the two parameters for the Wolfe conditions. Besides that the Springer book Numerical Optimization suggests these exact values for c_1 and c_2, is there a better way to choose them? Sometimes I got line search failed errors, that I cannot fully explain, so I appreciate any comments on the line search algorithm as well.

**Comment by debasish83** [comment]
@eidonfiloi could you please join our discussion on https://github.com/scalanlp/breeze/pull/364 SPG and PQN needs a different GradientConvergence than what is implemented in FirstOrderMinimizer right now...

**Comment by dlwh** [comment]
i think this is probably solved now that we can specify convergence criterion and can pick relative vs. absolute tolerances.
