### ISSUE TITLE
mean not defined for Transpose[DenseVector - missing implicit?

### ISSUE THREAD

**Issue by drdozer** [scalanlp/breeze#343]
could not find implicit value for parameter impl: breeze.stats.mean.Impl[breeze.linalg.Transpose[breeze.linalg.DenseVector[Double]],VR]
[error]       val me = mean(x_i)

in:

```scala
val x_i = x(i, ::)
val me = mean(x_i)
```

Presumably there's an implicit missing for T[DV] that chains onto the implicit for DV and unwraps the transposition?

This is worked around by calling:
```scala
mean(x_i.t)
```

**Comment by dlwh** [comment]
yeah  I need to add some lifting implicits for Transpose
