### ISSUE TITLE
Double * DenseVector[Double] not found

### ISSUE THREAD

**Issue by drdozer** [scalanlp/breeze#346]
The `*` operator seems to be defined for `DenseVector[Double] * Double`, but not for `Double * DenseVector[Double]`. Is this an oversight or intentional?

Cheers.

**Comment by dlwh** [comment]
Somewhere in between? I'm aware of it, but haven't taken any steps to fix
it. :-)

It requires a magic import to work (you have to have an implicit conversion
for Double), and I've generally tried to avoid magic imports. But this is
one place where I'm willing to make an exception

- David
