### ISSUE TITLE
Adding sparse matrix to dense matrix

### ISSUE THREAD

**Issue by danielkorzekwa** [scalanlp/breeze#348]
Adding sparse matrix to dense matrix is not working in breeze, e.g.
``` scala
val a = DenseMatrix((2,2),(3,3))    
val b = CSCMatrix((2,2),(3,3)) 
a + b //no such method
```

I could eventually work with vectors, but adding matrices as above would be much better.
```scala
val v1 = DenseVector(1,2) 
val v2 = SparseVector(3,4)     
v1 + v2
```

**Comment by dlwh** [comment]
shouldn't be hard to had. I'll get there.

(FWIW, a static cast to Matrix for both arguments will work...)
