### ISSUE TITLE
Matrix multiplication is slow.

### ISSUE THREAD

**Issue by invkrh** [scalanlp/breeze#355]
Hi,

I have 2 DenseMatrix[Int] of 1000*1000

The multiplication of them takes more than 20 seconds, however, when doing the same thing with Pandas(Python), it takes just 2 seconds. The difference is huge.

FYI, the two tests are done on the same PC with scala-2.10.4, python-2.7.6

I have no idea on it. Any insight ?

Hao.

**Comment by dlwh** [comment]
So, I didn't spend any time optimizing matrix multiply, and just
piggy-backed off the float/double implementations in netlib-java. So,
probably if you switched to Double (which gives no loss of precision from
Int) you'll get most of the speed back.

**Comment by dlwh** [comment]
Also, be sure to depend on the natives subproject.

And let's leave this open as a reminder that someone (maybe me) needs to
fix matrix multiply for Int and Long.

-- David

**Comment by invkrh** [comment]
@dlwh  

It's true. Double gets the speed back. It takes just 0.7s for multiplication.

Thank you.

**Comment by dlwh** [comment]
(1000x1000 is now about 650ms on my machine with Ints, down from 1.7s.)

**Comment by invkrh** [comment]
Nice! Thank you for the quick fix. =)

**Comment by marwanRiad** [comment]
can send me implementation
