### ISSUE TITLE
Examples for breeze.optimize

### ISSUE THREAD

**Issue by fayimora** [scalanlp/breeze#358]
Are there any examples somewhere about the above mentioned package? Looks like a very useful package but cant figure out how to use it.

**Comment by dlwh** [comment]
take a look at https://github.com/scalanlp/breeze/wiki/Quickstart#breezeoptimize and the unit tests for the optimize package, and probably just anything on github that uses breeze.optimize: https://github.com/search?l=scala&q=breeze.optimize&ref=simplesearch&type=Code&utf8=%E2%9C%93

**Comment by fayimora** [comment]
ok thanks!
