### ISSUE TITLE
`+` infix operator error for scalar + vector addition

### ISSUE THREAD

**Issue by pbugnion** [scalanlp/breeze#393]
The following leads to a compile time error

    scala> val v = Vector(1,2,3)
    scala> 2 + v
    <console>:12: error: overloaded method value + with alternatives:
       (x: Double)Double <and>
       [snip]
       (x: String)String
       cannot be applied to (breeze.linalg.Matrix[Int])

By comparison, all the other operators seem to work:

    scala> 2 * v
    breeze.linalg.DenseVector[Int] = DenseVector(2, 4, 6)

The same error occurs with a matrix.

**Comment by pbugnion** [comment]
I'm happy to have a go at fixing this, if someone points me in the right direction. I think I understand how the implicit `InjectNumericOps` class injects the implicits to 'pimp' Scala scalar types, but I'm not sure I understand quite how the operators are defined in `DenseVectorOps.scala`.

**Comment by dlwh** [comment]
Sorry about the slow reply. It's been a rough couple of weeks.

You can use :+, but + seems to interact badly with Predef's any2StringAdd,
so I gave up on it.

-- David

**Comment by dlwh** [comment]
If you can make it work, happy to accept the patch

**Comment by pbugnion** [comment]
Ah I see. Thanks.
