### ISSUE TITLE
Unary negation on Boolean vectors throws an exception.

### ISSUE THREAD

**Issue by pbugnion** [scalanlp/breeze#394]
scala> import breeze.linalg._

    scala> val b = Vector(true, false, false)

    scala> ! b
    <console>:11: error: ambiguous implicit values:
    both method mapUFuncImpl in object Vector of type [Tag, V, U](implicit impl:     breeze.generic.UFunc.UImpl[Tag,V,U], implicit canMapValues: breeze.linalg.support.CanMapValues[breeze.linalg.Vector[V],V,U,breeze.linalg.Vector[U]])breeze.generic.UFunc.UImpl[Tag,breeze.linalg.Vector[V],breeze.linalg.Vector[U]]
    and method fromLowOrderCanMapValues in trait MappingUFunc of type [T, V, V2, U](implicit handhold: breeze.linalg.support.CanMapValues.HandHold[T,V], implicit impl: breeze.linalg.operators.OpNot.Impl[V,V2], implicit canMapValues: breeze.linalg.support.CanMapValues[T,V,V2,U])breeze.linalg.operators.OpNot.Impl[T,U]
    match expected type breeze.linalg.operators.OpNot.Impl[breeze.linalg.Vector[Boolean],That]
              ! b 

Am I doing something wrong?

**Comment by rakeshchalasani** [comment]
Vector is a trait, and I am mot sure if Ufuncs work on traits, I don't think there are any implicit conversions to concrete types. Its better to stick with concrete classes, DenseVector or SparseVector to avoid such errors.

**Comment by dlwh** [comment]
Sorry for the really slow response. Just a bug. This should work.

**Comment by dlwh** [comment]
(In general working with Vector should work, though it's less likely to be
as good as picking one of the implementations concretely / using type
parameters and implicit UFunc Impls)
