### ISSUE TITLE
FirstOrderMinimizer / Adaptive Gradient Descent & AdaDelta

### ISSUE THREAD

**Issue by bashimao** [scalanlp/breeze#396]
I am currently developing code that adapts series of parameters using AGD with regularization. However, I noticed that your implementation differs from my original Matlab code in one significant point. 

Your order of execution is:
(1) initialState => initializes history to zero-vector, calls calculateObjective and adjust to create the initial state
(2) chooseDescentDirection
(3) determineStepSize
(4) takeStep => i.e. computes new weights
(5) calculateObjective => i.e. compute gradients
(6) adjust => i.e. create a copy of the gradients that includes regularization
(7) updateHistory => i.e. update the buffer that contains the least squares
(8) goto (2)

As you can see, the very first gradients are computed within initialState. They are lost and not stored in the history. What is the justification for throwing away the first set of gradients in all minimizers (this code is in FirstOrderMinimizer and usually not overwritten). I checked the original paper (Duchi, 2011) and the AdaDelta paper (Zeiler, 2012, which apparently introduces the "decaying" window you use) and could not really find any evidence that they do this.

Well my question would be... Do you not store the first gradients in the history because:
a) There is a mathematical justification that I am not aware of
b) Other algorithms that depend on the FirstOrderMinimizer require this constraint.
c) Numerical reasons; for example: I could imagine that - considering one starts with random weights - the first gradient could sometimes be comparatively large.
d) It is a mistake!
e) Other reasons?

**Comment by bashimao** [comment]
Update:
Another observation:

Let's presume that the we are in 2nd iteration. So the first gradient has been discarded. The second gradient is stored in the state and it's squared representation is in the history. Now we enter "takeStep". The first operation is now (L2 regularization):

val s = sqrt(state.history.sumOfSquaredGradients :+ (state.grad :* state.grad))

So, we square the previously stored last gradient to the history value. That means that the most recently computed gradient is considered twice. I cannot see, how that fits with the original AdaGrad algorithm. What do you think?

**Comment by dlwh** [comment]
I don't think this is quite right:

>(1) initialState => initializes history to zero-vector, calls calculateObjective and adjust to create the initial state
>(2) chooseDescentDirection
> (3) determineStepSize
>(4) takeStep => i.e. computes new weights
> (5) calculateObjective => i.e. compute gradients
> (6) adjust => i.e. create a copy of the gradients that includes regularization
> (7) updateHistory => i.e. update the buffer that contains the least squares
> (8) goto (2)
>
>As you can see, the very first gradients are computed within initialState. They are lost and not stored in the history. 

There's a bit of redundancy in the calculations, but note that at iteration 0, "takeStep" includes the gradient at time 0: 
```scala
     val s = sqrt(state.history.sumOfSquaredGradients :+ (state.grad :* state.grad))
      val newx = x :* s
      axpy(stepSize, dir, newx)
      s += (delta + regularizationConstant * stepSize)
      newx :/= s
      newx
```

That extra `state.grad :* state.grad` is the gradient from the current state (in iteration 0, the initialState).
That information is then incorporated into "sumOfSquaredGradients" in the 0'th updateHistory, which takes the gradient for the "oldState" (i.e. the initialState) and adds its square into the history.
