### ISSUE TITLE
Implement subLBFGS

### ISSUE THREAD

**Issue by devesh** [scalanlp/breeze#403]
An implementation of subLBFGS would be useful for training SVMs.

Paper: http://www.jmlr.org/papers/volume11/yu10a/yu10a.pdf
C++ Implementation (MPL licensed): https://code.google.com/p/shapematching/source/browse/trunk/cppcode/swBMRM/bmrm-2.1/solver/sublbfgs.cpp

**Comment by dlwh** [comment]
thanks. MPL code can't be directly included in apache-licensed code bases,
if i understand correctly, but the pseudocode looks simple enough

**Comment by dlwh** [comment]
also, I remember seeing this paper before. The need for a descent direction oracle makes this algorithm fairly specialized in terms of where it can be used.

**Comment by dlwh** [comment]
alternatively http://people.orie.cornell.edu/aslewis/publications/13-nonsmooth.pdf looks easier and doesn't require an oracle
