### ISSUE TITLE
Summing up collections of vectors

### ISSUE THREAD

**Issue by danielkorzekwa** [scalanlp/breeze#410]
Could we make it working?

e.g.   val x = (1 to 10).map(i => DenseMatrix(i)).sum

or sum(collection of vectorsmatrices)

**Comment by rakeshchalasani** [comment]
IMHO, functions on Scala collections seems odd to have in numerical library, particularly when you can do something like:

val x = (1 to 10).map(i => DenseMatrix(i)).reduce(_ + _)

**Comment by dlwh** [comment]
Yeah, .sum won't happen. But we can probably add a ufunc implementation for
sum

**Comment by danielkorzekwa** [comment]
Yea, probably you are right, but still, devs like me needs some ways for such stuff. Currently I use my own implict around Array[DenseVector]

Reduce won't work for collection of size 1 (I wrap reduce within implicit to make the code simpler)

How would that work with ufunc, from a user point of view?

The more specific use case I need it for is computing natural gradient in canonical parametrisation,
Nguyen et al. Collaborative Multi-output Gaussian Processes, 2014
http://auai.org/uai2014/proceedings/individuals/159.pdf

eq. 19, see summation over P

**Comment by dlwh** [comment]
(added sum(_) for collections of things that can be added)
