### ISSUE TITLE
Expand documentation on which operations copy the data

### ISSUE THREAD

**Issue by strelec** [scalanlp/breeze#412]
Currently, the wiki only says that some effort is made that unnecessary copying is avoided. However, that doesn't really tell much, since questions like this might arise.

1. Does vertcat make a copy or uses existing matrices?
2. Does (::, 1) make a copy for a vector or just create a view?
3. When does slicing make a copy?
4. And so on for all the operations...

I guess this would also depend on the backend (java vs BLAS).

p.s: I am making an effort to create a simple machine learning library, so questions like this are very important: https://github.com/strelec/QuantumLearn

**Comment by dlwh** [comment]
Fair enough. In general the rules are

1. Slicing always produces views.
1. Concatenation etc never produce views.
1. .asDenseMatrix and other "as" methods produce views. 
1. ".to" methods produce copies.
1. .flatten and .reshape take an optional parameter that govern whether they produce views. By default they prefer to produce views, but will produce a copy if the structure of the matrix isn't amenable (which is basically "is the current matrix represented by a contiguous block of memory?")
1. fliplr/flipud produce views.
1. Everything else I can think of produces copies.

Is that reasonably clear? I think it's complete.

**Comment by strelec** [comment]
Thank you.

Two questions:

1. Slicing always produces views. That is true, only if the slice area is contiguous? matrix(::, 1 to 100 by 3) doesn't produce a view, I assume?

2. How do the sliced matrices operate under native (netlib) backend? If I have a huge matrix, then splice out its last row and do a multiplication with that matrix, no unnecessary copying is made, if I understand correctly?

**Comment by dlwh** [comment]
1) It's still a view. There's actually a limitation where matrix(1 to 100 by 3, ::) won't work unless matrix.isTranspose arising from the implementation details imposed by blas. I mean to work around it one day.

2) Yes. BLAS is always used for mmul for float and double matrices.

**Comment by strelec** [comment]
I have been bechmarking and experimenting today. These two things are still not clear:

1.) mat(0 to -2, 0 to -2) seems like a O(n) operation (time increases at mat increases in size). Why?

2.) How is it possible to make efficient BLAS operations on mat(::, 0 to -1 by 10) and also not copying the data into new matrix?

Offtopic: Why do you get a row matrix when you call DenseVector.toDenseMatrix?

**Comment by dlwh** [comment]
On Sun, Jul 5, 2015 at 6:48 AM, Rok Kralj <notifications@github.com> wrote:

> I have been bechmarking and experimenting today. These two things are
> still not clear:
>
> 1.) mat(0 to -2, 0 to -2) seems like a O(n) operation (time increases at
> mat increases in size). Why?
>

That shouldn't happen. Can you share the code?


> 2.) How is it possible to make efficient BLAS operations on mat(::, 0 to
> -1 by 10) and also not copying the data into new matrix?
>

So, BLAS can support matrix operations when the leading dimension of the
matrix (usually columns) has a "major stride" >= size of the minor axis
(usually rows) that specifies how many items to jump. So that would produce
a matrix with majorStride == 10 * numRows.

Obviously there's less cache coherency than on a totally flat matrix, but
for one-off operations it's certainly faster than copying and doing the
operation


> Offtopic: Why do you get a row matrix when you call
> DenseVector.toDenseMatrix?
>

Um, that's a good question.
