### ISSUE TITLE
mapActiveValues on upcasted SparseVector does not work correctly

### ISSUE THREAD

**Issue by bashimao** [scalanlp/breeze#414]
The following two calls should actually behave the same:

<pre>
import breeze.linalg._
val a = SparseVector.zeros[(Double, Long)](10)
a.update(3, 10.0 -> 7)
a.update(6, 10.0 -> 7)
a.update(7, 10.0 -> 7)

// Direct call on SparseVector; This is the expected behavior!
a.mapActiveValues(x => {println(x); x } )
(10.0,7)
(10.0,7)
(10.0,7)

// Casting SparseVector to Vector; This is not what one would expect!
val b: Vector[(Double, Long)] = a
b.mapActiveValues(x => {println(x); x } )
null
null
null
(10.0,7)
null
null
(10.0,7)
(10.0,7)
null
null
</pre>

**Comment by bashimao** [comment]
Just saw something in the debugger:
<pre>
scala> b
res14: breeze.linalg.Vector[Double] = SparseVector((4,2.0), (6,5.0))

scala> b.activeValuesIterator.foreach(x => { println(s"$x"); x})
2.0
5.0
</pre>

So a temporary (quick&dirty) solution could be to replace the function body of <code>mapActiveValues()</code> with <code>this.activeValuesIterator.map(fn)</code>.

**Comment by dlwh** [comment]
fixed
