### ISSUE TITLE
breeze.plot error and plot two denseVectors against each other

### ISSUE THREAD

**Issue by ehsanmok** [scalanlp/breeze#415]
In (moved back to breeze) breeze-viz example https://github.com/scalanlp/breeze/wiki/Quickstart, scala console outputs "error:  object plot is not a member of package breeze" when I run "import breeze.plot._"

According to the Breeze and Visualization section here https://github.com/scalanlp/breeze/wiki/ScalaNLP-Project, I guess, there's no support for 2d plot of two denseVectors against each other, am I right?

P.S. I've looked at scalala and it seems it doesn't support scalaVersion 2.11.5. Any idea?
Thanks in advance

**Comment by dlwh** [comment]
you're missing the breeze-viz dependency, which is packaged separately.

    "org.scalanlp" %% "breeze-viz" % "0.11.2",

breeze.plot.plot(xs, ys) should do what you want.

Scalala is dead.

**Comment by ehsanmok** [comment]
Thank you. I should've double checked the dependencies. I also suggest to add this to the README to be more easy to start.

**Comment by dlwh** [comment]
good idea. done.

Thanks!
