### ISSUE TITLE
RegressionResult is defined twice

### ISSUE THREAD

**Issue by nightscape** [scalanlp/breeze#416]
Trait Regression is defined [here](https://github.com/scalanlp/breeze/blob/149b3655977eb9dea38b53a18b83d0a4e0e08d41/math/src/main/scala/breeze/stats/regression/RegressionResult.scala) and [here](https://github.com/scalanlp/breeze/blob/149b3655977eb9dea38b53a18b83d0a4e0e08d41/math/src/main/scala/breeze/stats/regression/package.scala).
Is there any specific reason for that? From time to time I get a compilation error from that, although sometimes it doesn't seem to matter...

**Comment by dlwh** [comment]
dunno. feel free to clean it out.

**Comment by dlwh** [comment]
apparently tihs was fixed.
