### ISSUE TITLE
Operations between Complex Vector and Scalar doesn't work

### ISSUE THREAD

**Issue by rakeshnd** [scalanlp/breeze#417]
While doing this
```
new DenseVector(Array(Complex(1,2))) + 1.0
```
throws
"could not find implicit value for parameter op: breeze.linalg.operators.OpAdd.Impl2[breeze.linalg.DenseVector[breeze.math.Complex],Double,That]"

However, this works,
```
Complex(1,2) + 1.0
```

**Comment by dlwh** [comment]
Breeze almost never supports operations on mixed types. Too much pain/code
duplication for now.

-- David

**Comment by rakeshnd** [comment]
Thanks! Closing this for now then.

**Comment by dlwh** [comment]
cool. It's something I'm aware isn't ideal. I'm trying to figure out the
right solution. I have a few ideas, but not much time to try them.
