### ISSUE TITLE
3 component operations

### ISSUE THREAD

**Issue by bashimao** [scalanlp/breeze#425]
It would be nice (sometimes probably even very fast) if we would have the ability to specify a destination of the product of <code>dv * dv.t</code>, <code>dv * dm</code>, <code>dm * dv</code> and <code>dm * dm</code> will be summed up. i.e. I want to have the ability to provide an existing matrix (of the right dimensions of course) to avoid small memory allocations when convolving a fancy kernel over my data.

So something like this:
<pre>
mul.inPlace(dst: DenseMatrix[T], src0: DenseVector[T], src1: Transpose[DenseVector[T]])
mul.inPlace(dst: DenseMatrix[T], src0: DenseMatrix[T], src1: DenseMatrix[T])
</pre>

You already have something similar with "scaleAdd => axpy". How difficult would it be to add such a thing for mul (with BLAS support of course!)

**Comment by dlwh** [comment]
This is #389

**Comment by dlwh** [comment]
(but yes, I agree it would be very useful!)

**Comment by dlwh** [comment]
actually, i've started to work on something related. I'll push the branch

**Comment by dlwh** [comment]
https://github.com/scalanlp/breeze/tree/fusion
