### ISSUE TITLE
Implement a `hashCode()` function in dense vector

### ISSUE THREAD

**Issue by pyetras** [scalanlp/breeze#428]
It could be a simple function based on [`List.hashCode()`](http://download.oracle.com/javase/6/docs/api/java/util/List.html#hashCode%28%29):

```
  override def hashCode(): Int = valuesIterator.foldLeft(1)((acc, obj) => 31*acc + (if (obj==null) 0 else obj.hashCode()))
```

**Comment by dlwh** [comment]
I recently added one (on Vector). It's a bit different than yours, because
it skips over 0s (which makes SparseVector hashcode computation fast, but
preserves the hashcode contract since SparseVector and DenseVector can be
.equals)

**Comment by dlwh** [comment]
(it's in 0.12-SNAPSHOT)
