### ISSUE TITLE
normalize() and norm() for Vector[Float]

### ISSUE THREAD

**Issue by carschno** [scalanlp/breeze#432]
I understand that both `breeze.linalg.normalize()` and `breeze.linalg.norm()` are implemented only for `Vector[Double]` and `Vector[Int]` types. However, these methods should also be applicable for `Vector[Float]` types. To my understanding, this should be straight-forward to do in the same fashion as for the other types.

**Comment by dlwh** [comment]
Mysteriously, it works so long as the scalar argument is a double:

```
scala> val v = Vector[Float](1.0f, 2.0f)
v: breeze.linalg.Vector[Float] = DenseVector(1.0, 2.0)

scala> norm(v, 2.0)
res3: Double = 2.23606797749979

scala> norm(v)
res4: Double = 2.23606797749979

scala> norm(v, 2.0f)
<console>:12: error: could not find implicit value for parameter impl:
breeze.linalg.norm.Impl2[breeze.linalg.DenseVector[Float],Float,VR]
              norm(v, 2.0f)
```

This needs to be fixed, of course

**Comment by carschno** [comment]
Thanks for fixing that! Does this imply that normalize() will also work on a Vector[Float]? (I suppose these should actually have been two different issues)

**Comment by dlwh** [comment]
it's also fixed. :)
