### ISSUE TITLE
Cannot foreach over broadcasted rows

### ISSUE THREAD

**Issue by strelec** [scalanlp/breeze#435]
```scala
mat(*, ::).foreach { row =>
   // do something
}
```

```
Error:(42, 18) could not find implicit value for parameter cmv: breeze.linalg.support.CanForeachValues[breeze.linalg.BroadcastedRows[breeze.linalg.DenseMatrix[Double],breeze.linalg.DenseVector[Double]],breeze.linalg.DenseVector[Double]]
```

**Comment by saurfang** [comment]
I have the same question and couldn't find a solution online.

**Comment by dlwh** [comment]
fixed! Not 100% happy with how broadcasted works right now. I'm tempted to make mat(*, ::) more or less a Vector[DenseVector[T]], which might simplify a lot of things.

**Comment by saurfang** [comment]
This is great. Thanks!

**Comment by danielkorzekwa** [comment]
hmm, it is not working for me,  using "org.scalanlp" %% "breeze" % "0.12-SNAPSHOT" on scala 2.11

```scala
 val x = DenseVector.rangeD(1, 4000,1).toDenseMatrix.t
 x(*,::).foreach{ row =>   println(row) }
```
errors:
Description	Resource	Path	Location	Type
could not find implicit value for parameter cmv: breeze.linalg.support.CanForeachValues[breeze.linalg.BroadcastedRows[breeze.linalg.DenseMatrix[Double],breeze.linalg.DenseVector[Double]],breeze.linalg.DenseVector[Double]]	CovSEisoTest.scala	/bayes-scala-gp/src/test/scala/dk/gp/cov	line 31	Scala Problem


Description	Resource	Path	Location	Type
not enough arguments for method foreach: (implicit cmv: breeze.linalg.support.CanForeachValues[breeze.linalg.BroadcastedRows[breeze.linalg.DenseMatrix[Double],breeze.linalg.DenseVector[Double]],breeze.linalg.DenseVector[Double]])Unit.  Unspecified value parameter cmv.	CovSEisoTest.scala	/bayes-scala-gp/src/test/scala/dk/gp/cov	line 31	Scala Problem
