### ISSUE TITLE
Why is the matrix calcs so slow

### ISSUE THREAD

**Issue by mrkaspa** [scalanlp/breeze#447]
I'm using osx and the native extensions

```scala
libraryDependencies ++= Seq(
  "org.scalanlp" %% "breeze" % breezeVersion,
  "org.scalanlp" %% "breeze-viz" % breezeVersion,
  "org.scalanlp" %% "breeze-natives" % breezeVersion,
)
```

```scala
trait KNN {
  type MDouble = DenseMatrix[Double]
  type VDouble = DenseVector[Double]

  def classify(input: MDouble, dataSet: MDouble, labels: Array[Double], k: Int): Int = {
    var timestamp: Long = System.currentTimeMillis
    val dataSetSize = dataSet.rows
    val tiled: MDouble = tile(input, dataSetSize, 1) // tiled data set
    // calculates the distance => √(x2-x1)^ + (y2-y1)^
    val diffMat: MDouble = tiled - dataSet
    val sqDiffMat: MDouble = diffMat :^ 2.0
    val sqDistances: VDouble = sum(sqDiffMat(*, ::)) // sum per row
    val distances: VDouble = sqDistances :^ 0.5 // sqrt
    val sortedDistances: Seq[Int] = argsort(distances) // sort the arguments
    val mapAcc = (0 to k).map { i => labels(sortedDistances(i)) }.groupBy(identity).mapValues(_.size)
    val res = mapAcc.foldLeft((0.0, 0)) { (t, curr) => if (t._2 > curr._2) t else curr }
    var lastTimestamp: Long = System.currentTimeMillis
    println("elapsed time in answer")
    println((lastTimestamp - timestamp) / 1000d)
    res._1.toInt
  }
}
````
this algorithm takes about 0.15 seconds, and in numpy the same algorithm takes about 0.035, I'm testing with a bigger matrix about 1934 x 1024

**Comment by dlwh** [comment]
can you give me a self contained main method? what version of breeze are
you using?

**Comment by dlwh** [comment]
would be nice to have the numpy code for comparison too

**Comment by mrkaspa** [comment]
@dlwh Here is all the scala code https://github.com/mrkaspa/ScalaMLExamples/blob/master/src/main/scala/com/mrkaspa/ml/knn/ImageProc.scala and the python code is this one https://github.com/pbharrin/machinelearninginaction/blob/master/Ch02/kNN.py#L103

**Comment by dlwh** [comment]
Thanks. you're like the 3rd or 4th person who's asked about squared
distance. I guess it's time I figured it out.

**Comment by mrkaspa** [comment]
@dlwh does this only happens with squared distance? I thought it wasn't loading the native extensions

**Comment by dlwh** [comment]
broadcasting can be a bit slow. I'll check out what's going on this weekend.

It looks like you aren't running it multiple times. The JVM takes a while to warm up (and it has to load the .so natives on first use). Can you time it running 4-5 times? I imagine we'll still be behind, but it might be more fair.

**Comment by mrkaspa** [comment]
@dlwh I made some meassures and the instruction that takes much time is the tile method

elapsed time in tile(input, dataSetSize, 1)
0.228
elapsed time in tiled - dataSet
0.008
elapsed time in diffMat :^ 2.0
0.022
elapsed time in sum(sqDiffMat(*, ::))
0.03
elapsed time in sqDistances :^ 0.5
0.0
elapsed time in argsort(distances)
0.0

**Comment by dlwh** [comment]
great thanks. that'll be relatively easy to fix

**Comment by mrkaspa** [comment]
thanks, I'll be pending

**Comment by dlwh** [comment]
i made a few improvements. If you're not satisfied, could you specify the actual sizes of the matrices you're using rather than doing file io? Easier to reproduce

**Comment by dlwh** [comment]
also, don't use argsort if you just want the top k elements. use argtopk

**Comment by mrkaspa** [comment]
Great how can I test the improvements?

**Comment by mrkaspa** [comment]
The params

val tiled: MDouble = tile(input, dataSetSize, 1) // tiled data set

input = Matrix(1 x 1024)
dataSetSize = 1934

**Comment by dlwh** [comment]
sbt update (assuming 0.12-SNAPSHOT) and try it out

**Comment by mrkaspa** [comment]
@dlwh It improved a lot but numpy keeps being faster

scala >> 89.50 sec

python >> 44.79 sec

**Comment by dlwh** [comment]
just so i know: that's 89.5 seconds for how many repeats?

**Comment by mrkaspa** [comment]
It calls the same method 1934 times one per each file

**Comment by dlwh** [comment]
ok, here is a much better implementation from Breeze's point of view. First, we transpose (and copy) the data so that it's (1024 x 1934), which is better for breeze because it's column major. 

Then we use broadcasting for the subtraction rather than explicitly tiling.

```scala
      val diffMat = dataSet(::, *) - input
      val sqDiffMat = diffMat :^ 2.0
      val sqDistances = sum(sqDiffMat(::, *)) // sum per column
      val distances = sqDistances :^ 0.5 // sqrt
      val k = 5
      val sortedDistances = argtopk(distances.t *= -1.0, k) // sort the arguments
      val mapAcc = (0 until k).map { i => labels(sortedDistances(i)) }.groupBy(identity).mapValues(_.size)
      val res = mapAcc.foldLeft((0.0, 0)) { (t, curr) => if (t._2 > curr._2) t else curr }
      res._1.toInt
```

All in all this is about 5x faster on my machine.

**Comment by mrkaspa** [comment]
For this line

```scala
val diffMat = dataSet(::, *) - input
```

I get this compilation error:

```
Error:(29, 34) could not find implicit value for parameter op: breeze.linalg.operators.OpSub.Impl2[breeze.linalg.BroadcastedRows[breeze.linalg.DenseMatrix[Double],breeze.linalg.DenseVector[Double]],KNN.this.MDouble,That]
    val diffMat = dataSet(*, ::) - input
                                 ^

Error:(29, 34) not enough arguments for method -: (implicit op: breeze.linalg.operators.OpSub.Impl2[breeze.linalg.BroadcastedRows[breeze.linalg.DenseMatrix[Double],breeze.linalg.DenseVector[Double]],KNN.this.MDouble,That])That.
Unspecified value parameter op.
    val diffMat = dataSet(*, ::) - input
                                 ^
```

**Comment by dlwh** [comment]
input should be DenseVector, 1024 long.

**Comment by dlwh** [comment]
Did it work?

**Comment by mrkaspa** [comment]
The numbers are like this for this line of code

elapsed time in dataSet(*, ::) - vec
0.098 sec

elapsed time in dataSet(*, ::) - vec
0.135 sec

elapsed time in dataSet(*, ::) - vec
0.128 sec

**Comment by mrkaspa** [comment]
The hole method for doing all the KNN calculation in python takes 0.045 sec I think the problem is in that line it's slower than python may be they do that through the native library

**Comment by dlwh** [comment]
Like I said, Breeze is column-major, so you're much much much better off doing columnwise computations:

```
  def timeBroadcastSubtract(reps: Int) = {
    val dataSet = DenseMatrix.rand[Double](1024, 1934)
    val input = DenseVector.rand(1024)
    cforRange(0 until reps) { i =>
      // calculates the distance => √(x2-x1)^ + (y2-y1)^
      dataSet(::, *) - input
    }
  }

  def timeBroadcastRowSubtract(reps: Int) = {
    val dataSet = DenseMatrix.rand[Double](1934, 1024)
    val input = DenseVector.rand(1024)
    cforRange(0 until reps) { i =>
      // calculates the distance => √(x2-x1)^ + (y2-y1)^
      dataSet(*, ::) - input
    }
  }
```

The difference in those two methods:

```
[info]            benchmark    ms linear runtime
[info]    BroadcastSubtract  6.67 ====
[info] BroadcastRowSubtract 42.64 ==============================
```

That is, if you rearrange your computation, you can get an order of magnitude speedup.

**Comment by dlwh** [comment]
(this is just how caches work on modern cpus. I could have made Breeze row-major like numpy, but it's too late to change it now.)

**Comment by mrkaspa** [comment]
But I'll have to rethink the solution to use column-wise operations rather than row-wise operations then

**Comment by dlwh** [comment]
i pasted in the solution earlier?

**Comment by mrkaspa** [comment]
Uhm I mean I'll have to change how the solution is implemented to take advance of the speed of the column-wise faster operations
