### ISSUE TITLE
Add methods for Add/Subtract between dense and CSC matrices.

### ISSUE THREAD

**Issue by bashimao** [scalanlp/breeze#451]
See code below:

<pre>
scala> import breeze.linalg._
scala> val x = DenseMatrix.ones[Double](10, 10)
scala> val y = CSCMatrix.zeros[Double](10, 10)
scala> y(5, 5) = 5
scala> x - y
<console>:27: error: could not find implicit value for parameter op: breeze.linalg.operators.OpSub.Impl2[breeze.linalg.DenseMatrix[Double],breeze.linalg.CSCMatrix[Double],That]
              x - y
                ^
scala> y - x
<console>:27: error: could not find implicit value for parameter op: breeze.linalg.operators.OpSub.Impl2[breeze.linalg.CSCMatrix[Double],breeze.linalg.DenseMatrix[Double],That]
              y - x
</pre>

**Comment by bashimao** [comment]
Update: Same issue with <code>:=</code> operator.

**Comment by dlwh** [comment]
bleh. this would all be so much easier if contravariance and implicits
wasn't so totally broken

**Comment by dlwh** [comment]
(actually addition already worked, bizarrely)

**Comment by dlwh** [comment]
(fixed)
