### ISSUE TITLE
Cleaner/more efficient breeze.linalg.DenseVector -> scala.collection.immutable.Seq ?

### ISSUE THREAD

**Issue by xanderdunn** [scalanlp/breeze#452]
I'm serializing a `DenseVector[Float]` to a Protobuf class `Prediction`, which takes `scala.collection.immutable.Seq[Float]`.  This is what I'm currently doing: 

```scala
  def serializeOutput(output: DenseVector[Float]) : Prediction = {
    val outputSeq = mutable.ArrayBuffer[Float]()
    for {value <- output} {
      outputSeq += value
    }
    Prediction(output.length, immutable.Seq(outputSeq: _*))
  }
```

It works, but it's not particularly pretty, efficient, or functional.  I'm iterating through the entire `DenseVector` to create a mutable `ArrayBuffer` and then I'm making an immutable copy of that.  I'd prefer to get rid of that mutable `ArrayBuffer` without sacrificing performance.  I wanted to do this: 

```scala
  def serializeOutput(output: DenseVector[Float]) : Prediction = {
    val outputSeq : immutable.Seq[Float] =
    (for {value <- output}
     yield value)(collection.breakOut)
    Prediction(output.length, outputSeq)
  }
```

However, this produces: 
```bash
/local/dev/odin-core/common/src/main/scala/ai/osaro/nn/Hierarchy.scala:114: polymorphic expression cannot be instantiated to expected type;
 found   : [From, T, To]scala.collection.generic.CanBuildFrom[From,T,To]
 required: breeze.linalg.support.CanMapValues[breeze.linalg.DenseVector[Float],Float,Float,scala.collection.immutable.Seq[Float]]
     yield value)(collection.breakOut)
```
It looks like it's not implemented on the breeze side. 

Anyone have better ideas?

**Comment by dlwh** [comment]
.toScalaVector should do what you want. it's not actually any more efficient, probably, but is it really your bottleneck?

**Comment by xanderdunn** [comment]
@dlwh Thanks a lot for that!  I didn't see it listed in the [docs for DenseVector](http://www.scalanlp.org/api/breeze/index.html#breeze.linalg.DenseVector).  

I haven't actually measured this is a bottleneck, so mostly I was just looked for less messy implementation.  `toScalaVector` does it!
