### ISSUE TITLE
How do I verify if the native libs are loaded?

### ISSUE THREAD

**Issue by davidshen84** [scalanlp/breeze#453]
I am working on Windows 64 bit environment. I have added this:

    "org.scalanlp" %% "breeze-natives" % "0.10"

to my scala project dependencies. But how do I verify the natives libs are loaded and working? I remember in Spark environment, it will warning me if native libs are loaded, and Spark uses **breeze** for matrix operations. So I wonder why I am not seeing similar messages when using **breeze**.

**Comment by dlwh** [comment]
assert(breeze.linalg.usingNatives)

**Comment by davidshen84** [comment]
brilliant, thx!


On Wed, Oct 7, 2015 at 2:04 PM David Hall <notifications@github.com> wrote:

> assert(breeze.linalg.usingNatives)
>
> On Tue, Oct 6, 2015 at 10:27 PM, Xi Shen <notifications@github.com> wrote:
>
> > I am working on Windows 64 bit environment. I have added this:
> >
> > "org.scalanlp" %% "breeze-natives" % "0.10"
> >
> > to my scala project dependencies. But how do I verify the natives libs
> are
> > loaded and working? I remember in Spark environment, it will warning me
> if
> > native libs are loaded, and Spark uses *breeze* for matrix operations. So
> > I wonder why I am not seeing similar messages when using *breeze*.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scalanlp/breeze/issues/453>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalanlp/breeze/issues/453#issuecomment-146085588>.
>
-- 

Regards,
David
