### ISSUE TITLE
Weird behavior to create a matrix

### ISSUE THREAD

**Issue by mrkaspa** [scalanlp/breeze#454]
How can I create a matrix from an Array of Arrays, I tried this:

new DenseMatrix(2, 3, Array(11, 12, 13, 21, 22, 23))
res0: breeze.linalg.DenseMatrix[Int] =
11  13  22
12  21  23

But I think this should work this way:

new DenseMatrix(2, 3, Array(11, 12, 13, 21, 22, 23))
res0: breeze.linalg.DenseMatrix[Int] =
11  12  13
21  22  23

I think this is the way It should work

**Comment by dlwh** [comment]
```scala
scala> import breeze.linalg._
import breeze.linalg._

scala> val dm = DenseMatrix(Array(Array(1,2,3), Array(1,2,3)):_*)
dm: breeze.linalg.DenseMatrix[Int] =
1  2  3
1  2  3
```

**Comment by dlwh** [comment]
(It's not clear what you want since you copied the same code twice, but this is the way breeze works.)

**Comment by mrkaspa** [comment]
I wanted to create a matrix from an array of arrays, the snippet to creare one from a big array is the one that is in the scala doc. I think that method should work like this from saddle

scala> Mat(2,2, Array(1,2,3,4))
res41: org.saddle.Mat[Int] =
[2 x 2]
1 2
3 4

**Comment by dlwh** [comment]
other than being column major, how is that any different?

**Comment by dlwh** [comment]
or rather, row major instead of column major?

**Comment by dlwh** [comment]
and that's not an array of arrays?

**Comment by dlwh** [comment]
ah i see, you are precisely unhappy about row major vs. column major. Breeze is column major. it's too late to change it.

if you want, you can do `new DenseMatrix(2, 3, Array(11, 12, 13, 21, 22, 23), isTranspose = true)`

**Comment by dlwh** [comment]
err, 

scala> new DenseMatrix(2, 3, Array(11, 12, 13, 21, 22, 23), 0, 3, isTranspose = true)
res2: breeze.linalg.DenseMatrix[Int] =
11  12  13
21  22  23

**Comment by mrkaspa** [comment]
Great I'll use the is transponse feature thx
