### ISSUE TITLE
add isIdentical(.) and hasUncountable()

### ISSUE THREAD

**Issue by danielkorzekwa** [scalanlp/breeze#460]
like in SimpleMatrix in ejml,

either
```
hasUncountable(vector/matrix)
isIdentical(vector/matrix,tollerance)
```

or
```
m.isIdentical(m,tollerance)
m.hasUncountable():Boolean
```

**Comment by dlwh** [comment]
ok, i added support for these features, but they're a bit different:

`hasUncountable(v/m)` is `any(isNonfinite, v/m)`
`isIdentical(v1, v2, tol)` is `isClose(v1, v2, tol)`
