### ISSUE TITLE
support for symmetric matrices?

### ISSUE THREAD

**Issue by fommil** [scalanlp/breeze#461]
a colleague was considering using breeze, but it was lacking a symmetric dense matrix structure backed by `netlib-java` for the typical ops. Do you have any plans to implement this? If not, what would need to be done?

**Comment by dlwh** [comment]
It is a problem.

There are aspirations for this (along with rank 1 matrices), but I haven't
done it, and I don't have short term plans to do it.

What has to happen depends on the extent to which you want them to be
typesafe/integrated into breeze. In particular, matrices right now are
always mutable (i.e. they need an update(i,j) method), and that's probably
wrong for symmetric matrices.

Nevertheless, in Breeze, you don't have to extend Matrix to be useful as a
matrix. Many operations (though not all) that operate on "generic" matrices
accept an arbitrary type T so long as it comes with the appropriate type
class implementations. For example, svd(m, 10) will find the first 10
singular values of any m that supports multiplication by a dense vector and
transpose multiply by a dense vector.

Anyway, the simplest thing to do is to make a:

```scala
case class SymmetricMatrix[@specialized(Int, Float, Long, Double) T](data:
Array[T], dim: Int) extends NumericOps[SymmetricMatrix[T]]
```

and in the companion object implement various ops in the normal breeze way
with UFuncs and the like.

Generally, you're looking at implementing something like:

```scala
implicit object MulSymDD extends OpMulMatrix.Impl2[SymmetricMatrix[T],
DenseMatrix[T], DenseMatrix[T]] {
  override def apply(a: SymmetricMatrix[T], b:  DenseMatrix[T]):
DenseMatrix[T] = ???
}
```

Happy to provide skeletons for specific ops. (It is nearly halloween after
all!)

-- David

**Comment by rolloff** [comment]
+1 I would like this feature.

**Comment by fommil** [comment]
@rolloff if you have time, would you be interested in implementing this feature?
