### ISSUE TITLE
DenseMatrix(Double.PositiveInfinity)*DenseVector(0d) gives 0

### ISSUE THREAD

**Issue by danielkorzekwa** [scalanlp/breeze#463]
```
scala> DenseMatrix(Double.PositiveInfinity)*DenseVector(0d)
res31: breeze.linalg.DenseVector[Double] = DenseVector(0.0)
```

I would expect it to be NaN as

```
scala> Double.PositiveInfinity*0d
res36: Double = NaN
```

**Comment by dlwh** [comment]
i think that might just be blas. not sure what to do about it. We could do
a quick check over both to make sure there aren't any bad numbers, i guess,
but that seems expensive.

**Comment by danielkorzekwa** [comment]
not a big deal for me, I found it while replacing ejml with breeze, decide yourself,
there is a number of similar disparities between ejml and breeze, I guess all will be like this.

**Comment by dlwh** [comment]
Ok, I definitely appreciate the reports!

**Comment by danielkorzekwa** [comment]
sorry David, there were a few but I didn't write them down. one more I remember::

```
 DenseMatrix.eye[Double](2)*Double.PositiveInfinity
```

NaN on off diagional

**Comment by dlwh** [comment]
closing these as "blas is blas"
