### ISSUE TITLE
Matlab svds like implementation in breeze

### ISSUE THREAD

**Issue by burann** [scalanlp/breeze#466]
Is there a function in Breeze that works like Matlab svds()  ?

**Comment by nikdon** [comment]
You can use `svd` on `CSCMatrix`. That is similar to matlabs svds. Docs for the function is [here](https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/functions/svd.scala#L318). Another option is `svdr` [that you can use for dense matrices](https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/functions/svdr.scala#L32).

```scala
val m = CSCMatrix(
      (2.0,4.0,0.0,1.0,2.0),
      (1.0,0.0,2.0,1.0,0.0),
      (1.0,3.0,2.0,1.0,9.0),
      (0.0,0.0,2.0,0.0,5.0),
      (0.0,1.5,0.0,0.0,5.0),
      (1.5,0.0,2.0,0.0,5.0)
    )

val SVD(u, s, vt) = svd(m2, k)
```

```scala
val m = DenseMatrix(
      (2.0, 4.0, 0.0),
      (1.0, 3.0, 4.0),
      (5.0, 0.0, 0.9),
      (3.0, 5.0, 0.5),
      (7.5, 1.0, 6.0),
      (0.0, 7.0, 0.0)
    )

val SVD(u, sr, vt) = svdr(m, k)
```

**Comment by dlwh** [comment]
svd(m, k) should work on dense matrices too.

-- David

**Comment by burann** [comment]
Thanks for clearing that up for me, much appreciated !
