### ISSUE TITLE
Operations Should Work on Generic Vector Type

### ISSUE THREAD

**Issue by carschno** [scalanlp/breeze#469]
As discussed [here](http://stackoverflow.com/questions/33690251/argmax-could-not-find-implicit-value), the `argmax` operation works on `SparseVector` and on `DenseVector`, but not on `Vector`. This might be true for other operations as well. Every vector operation should also work on the generic `Vector` type so that interfaces do not need to consider which implementation other methods use internally.

**Comment by dlwh** [comment]
I fixed operations like argmax yesterday, but yeah more work to do. I guess I should figure out a good way to enforce this programmatically

**Comment by dlwh** [comment]
OK, I now have a generic framework in place for ensuring that UFuncs support the various operations for types. There are known issues, but this 

All this would be so much easier if contravariance in Scala's implicit resolution wasn't totally broken.

**Comment by dlwh** [comment]
i'm going to close this because I have a framework in place for ensuring things like this don't happen. Coverage isn't perfect, I'm sure, but this bug isn't really actionable.
