### ISSUE TITLE
FirstOrderMinimizer functionValuesConverged and objectiveNotImproving function are the same

### ISSUE THREAD

**Issue by convexquad** [scalanlp/breeze#471]
I noticed that the code for the FirstOrderMinimizer functionValuesConverged function (https://github.com/scalanlp/breeze/blob/f4c326f9f219859156a8c55bc667369813fa4b52/math/src/main/scala/breeze/optimize/FirstOrderMinimizer.scala#L179) and the objectiveNotImproving function (https://github.com/scalanlp/breeze/blob/f4c326f9f219859156a8c55bc667369813fa4b52/math/src/main/scala/breeze/optimize/FirstOrderMinimizer.scala#L183) are the same.

By the name, the objectiveNotImproving function looks like it should obviously be doing something different - is this a bug?

**Comment by dlwh** [comment]
hrm, i thought i deleted objectiveNotImproving. Thanks for the report
