### ISSUE TITLE
Small issues in the Quickstart documentation

### ISSUE THREAD

**Issue by NarineK** [scalanlp/breeze#472]
I was looking at the quickstart documentation and have noticed some small issues.
Here is a short list. I hope it will be useful to improve the documentation.

1 .  In "breeze.optimize" section the line:
		scala> lbfgs.minimize(f,DenseVector(0,0,0)) 
	is repeated twice.

2 .  in the same section as 1., I think it should be : 
 res6: breeze.linalg.DenseVector[Double] = DenseVector(2.9999999999999973, 2.9999999999999973, 2.9999999999999973)
instead of 
"breeze.linalg.DenseVector[Double] = DenseVector(2.9999999999999973, 2.9999999999999973, 2.9999999999999973)"

because the res6 is being used later in: f(res6)

3 . In "breeze.optimize.linear" section I think an import is needed, otherwise it cannot find the "Real" class.
"import breeze.optimize.linear._"

4 . In "breeze.optimize.linear"  section  the example with assert - there is a small typo (I guess it should be 4.0 instead of 4.)

instead of
assert( (result.result - DenseVector(40.,17.5,42.5)).norm(2) < 1E-4)

should be:
assert( (result.result - DenseVector(40.0,17.5,42.5)).norm(2) < 1E-4)

**Comment by dlwh** [comment]
thanks, fixed!
