### ISSUE TITLE
Multiplication of Empty Matrix with Vector Fails

### ISSUE THREAD

**Issue by evolutics** [scalanlp/breeze#476]
Multiplying an empty matrix with a vector as in

```Scala
import breeze.linalg.DenseMatrix
import breeze.linalg.DenseVector

val rows = 0
val columns = 2
val emptyMatrix = DenseMatrix.zeros[Double](rows, columns)
val vector = DenseVector.zeros[Double](columns)
val matrixVectorProduct = emptyMatrix * vector // This fails.
```

fails with the error message

```
Parameter 7 to routine cblas_dgemv  was incorrect
```

But I would expect it to produce an empty vector instead, since the number of matrix columns matches the vector dimension – both are equal to `columns`.

On the other hand, if we change the sizes in the example to

```Scala
val rows = 3
val columns = 0
```

we get a vector of dimension `rows` as expected.

**Comment by evolutics** [comment]
In file [`DenseMatrixOps.scala` on line 86](../tree/master/math/src/main/scala/breeze/linalg/operators/DenseMatrixOps.scala#L86), changing `a.majorStride` to `a.majorStride.max(1)` seems to help. However, I am not sure how many more changes this needs.

**Comment by dlwh** [comment]
thanks!
