### ISSUE TITLE
Feature request: ODE Solver

### ISSUE THREAD

**Issue by jaketimothy** [scalanlp/breeze#478]
Is this something that fits in to breeze?  It's certainly in matlab and scipy.  If so, I'd love to have a solver that works with DenseVector.  

I'd be happy to start implementing a Runge-Kutta to begin with.

So far, I've found starting points [here](http://www.scalaformachinelearning.com/2013/06/generic-runge-kutta-functional-solver.html) and in [scalation.dynamics](https://github.com/scalation/scalation/tree/master/src/main/scala/scalation/dynamics).

**Comment by dlwh** [comment]
Definitely, I'd be happy to have one!

I'd probably take any of the numerical routines from that library

-- David
