### ISSUE TITLE
CSCMatrix Format - link to documentation mentioned in the source code seems to be unavailable

### ISSUE THREAD

**Issue by NarineK** [scalanlp/breeze#482]
It seems that the link mentioned in the CSCMatrix.scala  code documentation is no longer available: https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/CSCMatrix.scala#L51

Will "http://netlib.org/linalg/html_templates/node92.html#SECTION00931200000000000000" be a better link to the documentation? Although the format looks a little different from the  implementation in CSCMatrix.scala.

**Comment by dlwh** [comment]
should probably be this:
https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_column_.28CSC_or_CCS.29

**Comment by dlwh** [comment]
(just fixed)

**Comment by NarineK** [comment]
thnx
