### ISSUE TITLE
UFunc Median

### ISSUE THREAD

**Issue by vishalkuo** [scalanlp/breeze#483]
For documentation; I'd like to implement a ufunc median function as I've noticed there isn't one already.

**Comment by dlwh** [comment]
there actually is!

breeze.stats.median

It's only implemented for DenseVector and DenseMatrix

**Comment by vishalkuo** [comment]
My wording was vague, I meant I'd like to implement a ufunc median since the current implementation is only for dense vectors/matrices

**Comment by vishalkuo** [comment]
https://github.com/scalanlp/breeze/pull/485
