### ISSUE TITLE
A question about LBFGS.State.iter and the total number of iterations

### ISSUE THREAD

**Issue by NarineK** [scalanlp/breeze#484]
According to the source code, as far as I understand the initial iteration has iteration number 0.
Shouldn't it be 1 ? I was thinking so because the initial state is also being returned as part of loss history and states.length should be equal to states.last.iter  but right now states.last.iter = states.length-1 
What do you think ?

Thanks,
Narine

**Comment by dlwh** [comment]
I stick with the usual 0-based indexing used in most programming languages.
I don't think it's unreasonable to think of it as the zeroth iteration, is
it?

**Comment by NarineK** [comment]
I see, it seems to be a convention ... 
I have another question about the number of iteration which theoretically can be really large and this will lead to a very large array of states. Does the states array actually contain all states or only last k?
I cannot see in code that the states array is limited.
Sorry for too many questions ...

**Comment by dlwh** [comment]
no worries!

it's an iterator not an array, so states are discarded as soon as you stop
holding onto them (and the garbage collector runs)

**Comment by NarineK** [comment]
that sounds good! 
Thanks!
