### ISSUE TITLE
Normalizing on Int Dense/Sparse Vector

### ISSUE THREAD

**Issue by vishalkuo** [scalanlp/breeze#490]
Should calling normalize on an integer dense/sparse vector return a normalized double vector? Or throw a more descriptive exception? Not even sure if this is an issue; just wanted some clarification.

```scala
val x = DenseVector(1, 2, 3, 4, 5)
normalize(x)
```

which results in 
``` scala
 error: could not find implicit value for parameter impl: breeze.linalg.normalize.Impl[breeze.linalg.DenseVector[Int],VR]
       normalize(x)
```

**Comment by dlwh** [comment]
It's a compile error, and I don't have a ton of control over the error messages at the moment. I wish we could do something better, but hands are a bit tied right now.

In general, Breeze doesn't do a lot of "promotion" between numeric types. It puts too much strain on the way Breeze sues the type system. This should work, btw: `normalize(convert(x, Double)) `
