### ISSUE TITLE
Setting a random seed 

### ISSUE THREAD

**Issue by adgaudio** [scalanlp/breeze#492]
Hello!

I have a feature request, and would be happy to put up a PR if I receive positive feedback for it.

Currently, as far as I understand, it is a bit complicated to set a specific random seed for a probability distribution.  For instance:

```
import breeze.stats.distributions.{Uniform,RandBasis,ThreadLocalRandomGenerator}
import org.apache.commons.math3.random.{MersenneTwister}

def setSeed(seed: Int = 0) = {
      new RandBasis(new ThreadLocalRandomGenerator(new MersenneTwister(seed)))
}

val dist = new Uniform(0, 1)(setSeed())
```

I know that RandBasis.mt0 exists, but the actual seed value is an AtomicInteger, and not a configurable value.

```
val dist = new Uniform(0, 1)(RandBasis.mt0)
```
I would like to make it easier to configure the seed for Breeze distributions, and I propose defining the `setSeed` function above as a method on the RandBasis object, so we'd have `RandBasis.setSeed(seed: Int)` as an option in addition to `RandBasis.mt0`.  

I have 3 questions:

1. Is this a good idea?
2. Are there better ways or other ways to set a random seed?
3. Does it make sense for me to open a PR to add the RandBasis.setSeed method?

Thank you!

**Comment by dlwh** [comment]
Yeah, this is great, except:

1) I'd probably say "withSeed" or "seeded" or something instead of setSeed,
since it's not actually a setter.
2) The atomic integer is important because with your code every thread gets
its own random generator with the same seed.

I'd happily accept a PR with those changes.

-- David
