### ISSUE TITLE
L-BFGS-B bound error

### ISSUE THREAD

**Issue by lerad** [scalanlp/breeze#497]
I am currently working with the L-BFGS-B implementation. I basically used the code from the LBFGSB test case [(LBFGSBTest.scala)](https://github.com/scalanlp/breeze/blob/master/math/src/test/scala/breeze/optimize/LBFGSBTest.scala), which computes the Rosenbrock function:

``` scala
import breeze.linalg.DenseVector
import breeze.numerics.pow
import breeze.optimize.{LBFGSB, DiffFunction}

object LbfgsbExample2 {
  def main(args : Array[String]): Unit = {
    val solver = new LBFGSB(DenseVector[Double](-100, -100), DenseVector[Double](0.5, 100))
    val nearX0 = DenseVector[Double](-1.2, 1.0)

    val f = new DiffFunction[DenseVector[Double]] {
      override def calculate(x: DenseVector[Double]): (Double, DenseVector[Double]) = {
        val cost = (1-x(0))*(1-x(0)) + 100*pow(x(1) - x(0)*x(0), 2)
        val grad = DenseVector(
          -2.0*(1-x(0)) + 200*(x(1) - x(0)*x(0))*(-2.0*x(0)),
          200*(x(1) - x(0)*x(0))
        )
        (cost, grad)
      }
    }

    val optX = solver.minimize(f, nearX0)

    System.out.println("optX: %s".format(optX.toArray.mkString(",")))
  }
}
```

with the only change that I used `DenseVector[Double](0.5, 100)` as upper bound, instead of `DenseVector[Double](1200, 100)`.
I would have expected that it shows now another minimum, ((0.5, 0.25) according to another minimizer), but instead it shows the following exception:

> Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: seed is not feasible (violates lower bound or upperBounds)
>     at scala.Predef$.require(Predef.scala:219)
>     at breeze.optimize.LBFGSB.initialize(LBFGSB.scala:94)
>     at breeze.optimize.LBFGSB.initialHistory(LBFGSB.scala:55)
>     at breeze.optimize.LBFGSB.initialHistory(LBFGSB.scala:32)
>     at breeze.optimize.FirstOrderMinimizer$$anonfun$infiniteIterations$1.apply(FirstOrderMinimizer.scala:79)
>     at breeze.optimize.FirstOrderMinimizer$$anonfun$infiniteIterations$1.apply(FirstOrderMinimizer.scala:62)
>     at scala.collection.Iterator$$anon$7.next(Iterator.scala:129)
>     at breeze.util.IteratorImplicits$RichIterator$$anon$2.next(Implicits.scala:71)
>     at breeze.util.IteratorImplicits$RichIterator.last(Implicits.scala:84)
>     at breeze.optimize.FirstOrderMinimizer.minimizeAndReturnState(FirstOrderMinimizer.scala:106)
>     at breeze.optimize.FirstOrderMinimizer.minimize(FirstOrderMinimizer.scala:101)
>     at main.LbfgsbExample2$.main(LbfgsbExample2.scala:23)
>     at main.LbfgsbExample2.main(LbfgsbExample2.scala)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

But obviously -100 < -1.2 < 0.5 and -100 < 1.0 < 100. So the initial value (which I guess is meant by seed?) should fit to the bounds.

This happens with 0.13-SNAPSHOT and 0.12

**Comment by dlwh** [comment]
thanks, I'll try to look into this. This code is new and not perfectly
vetted yet.

In the meantime, you can try to use our ProjectedQuasiNewton minimizer.

**Comment by dlwh** [comment]
i can't reproduce this...

**Comment by dlwh** [comment]
nevermind, got it
