### ISSUE TITLE
The invariant requirement for SparseVectors and CSCMatrices is nonobvious

### ISSUE THREAD

**Issue by asevans48** [scalanlp/breeze#500]
Solution: we should probably make CSCMatrix and SparseVector do a sanity check by default, and allow people to disable it via a ctor flag.

---

Breeze version: 0.12
Scala: 2.11 (e.g. breeze_2.11)
Problem:  Data not reading when creating sparse vectors and CSC Matrices outside of provided arrays.

There is  a relatively serious issue when dealing with Sparse data formats in breeze. I am trying to interoperate between spark and breeze as needed to work on improving the accuracy of text algorithms. I have also built quite a few algorithms for my data using scala which do not exist in MLLib or for which I need to work on a single node. 

I am building the Vector and Matrix using arrays to save memory and improve speed (critical for my project).  I can create a Sparse Vector and CSC Matrix well enough for use with the dot product of the form a.t \* b but cannot seem to access the data without accessing the arrays themselves. I can even map the active values appropriately (giving me division, addition; etc.). Matrix(a,b) always yields 0.0. This is a relatively serious problem when trying to access specific values.

The following was pulled from the eclipse scala IDE but works the same in sbt. My enrichments using the Enrichment/Pimp My Library patterns work well enough as well (I can splice rows and columns accurately using the arrays I provided and return the appropriate breeze structure).

My code is available from the master at my [github.](https://github.com/asevans48/TextPreprocessors.git). It will be under com.simplrtek.hashing.FeatureHasher function getCSCMatrix.scala and com.siplrtek.Driver.TestDriver.scala

```
val sv = new SparseVector(indices.toArray,data.toArray,matrix.cols)

sv
SparseVector((273071,0.48497037369378937), (272643,0.48497037369378937), (22878,0.48497037369378937), (449535,0.48497037369378937), (346338,0.48497037369378937), (66779,0.0), (30148,0.48497037369378937), (191106,0.0))

sv.toDenseVector
DenseVector(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)

sv(273071)
Exception in thread "main" java.lang.IndexOutOfBoundsException: 273071 not in [0,21)
    at breeze.linalg.SparseVector$mcD$sp.apply$mcD$sp(SparseVector.scala:75)
    at com.simplrtek.hashing.ParallelFeatureHasher.getCSCMatrix(FeatureHasher.scala:186)
    at com.simplrtek.vectorizers.ParallelTFIDFVectorizer.getCSCMatrix(TFIDFVectorizer.scala:150)
    at com.simplrtek.Driver.HTestDriver$.main(TestDriver.scala:49)
    at com.simplrtek.Driver.HTestDriver.main(TestDriver.scala)

val csc = new CSCMatrix(values.toArray,mx ,vptrs.size ,vptrs.toArray,indices.toArray)

csc

449535 x 21 CSCMatrix
(411768,0) 2.3513752571634776
(91574,0) 2.3513752571634776
(233464,0) 2.3513752571634776
(256429,0) 2.3513752571634776
(273071,1) 0.48497037369378937
(272643,1) 0.48497037369378937
(22878,1) 0.48497037369378937
(449535,1) 0.48497037369378937
(346338,1) 0.48497037369378937
(66779,1) 0.0
(30148,1) 0.48497037369378937
(191106,1) 0.0
(385222,2) 0.40414197807815777
(92356,2) 0.40414197807815777
(66779,2) 0.0
(251343,2) 0.40414197807815777
(191106,2) 0.0
(273071,3) 0.48497037369378937
(272643,3) 0.48497037369378937
(22878,3) 0.48497037369378937
(449535,3) 0.48497037369378937
(346338,3) 0.48497037369378937
(66779,3) 0.0
(30148,3) 0.48497037369378937
(191106,3) 0.0
(385222,4) 0.40414197807815777
(92356,4) 0.40414197807815777
(66779,4) 0.0
(251343,4) 0.40414197807815777
(191106,4) 0.0
(273071,5) 0.48497037369378937
(272643,5) 0.48497037369378937
(22878,5) 0.48497037369378937
(449535,5) 0.48497037369378937
(346338,5) 0.48497037369378937
(66779,5) 0.0
(30148,5) 0.48497037369378937
(191106,5) 0.0
(385222,6) 0.40414197807815777
(92356,6) 0.40414197807815777
(66779,6) 0.0
(251343,6) 0.40414197807815777
(191106,6) 0.0
(273071,7) 0.48497037369378937
(272643,7) 0.48497037369378937
(22878,7) 0.48497037369378937
(449535,7) 0.48497037369378937
(346338,7) 0.48497037369378937
(66779,7) 0.0
(30148,7) 0.48497037369378937
(191106,7) 0.0
(385222,8) 0.40414197807815777
(92356,8) 0.40414197807815777
(66779,8) 0.0
(251343,8) 0.40414197807815777
(191106,8) 0.0
(273071,9) 0.48497037369378937
(272643,9) 0.48497037369378937
(22878,9) 0.48497037369378937
(449535,9) 0.48497037369378937
(346338,9) 0.48497037369378937
(66779,9) 0.0
(30148,9) 0.48497037369378937
(191106,9) 0.0
(385222,10) 0.40414197807815777
(92356,10) 0.40414197807815777
(66779,10) 0.0
(251343,10) 0.40414197807815777
(191106,10) 0.0
(273071,11) 0.48497037369378937
(272643,11) 0.48497037369378937
(22878,11) 0.48497037369378937
(449535,11) 0.48497037369378937
(346338,11) 0.48497037369378937
(66779,11) 0.0
(30148,11) 0.48497037369378937
//The text matrix is based on a single node TFIDF I built and my enrichment pattern can slice the //columns  and rows using the arrays but oddly not the slice.

//clearly wrong
csc(0 until csc.rows,11 to 11).activeIterator.toList.filter(_._2 > 0.0)
List(((272643,0),0.48497037369378937))

//again not the value posted in print
println(csc(22878,11))
0.0

assert(csc(22878,11) > 0.48 && csc(22878,11) <.49)
Exception in thread "main" java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:151)
    at com.simplrtek.hashing.ParallelFeatureHasher.getCSCMatrix(FeatureHasher.scala:190)
    at com.simplrtek.vectorizers.ParallelTFIDFVectorizer.getCSCMatrix(TFIDFVectorizer.scala:150)
    at com.simplrtek.Driver.HTestDriver$.main(TestDriver.scala:49)
    at com.simplrtek.Driver.HTestDriver.main(TestDriver.scala)
```

This is making the breeze library highly impractical for my projects but I would not like to switch and my several dozen gigabyte matrices are taking to long for online learning to  or not loading via stacking, pickling, or straight loading in numpy. 

Is it possible to resolve theses issues?

Thanks.

**Comment by dlwh** [comment]
wow those are some serious oversights. I will tackle these this weekend.

**Comment by dlwh** [comment]
(if not before, but pretty busy this week.)

**Comment by dlwh** [comment]
oh I see!

You are violating the invariants of these data structures. You have to
respect their formats when you pass in the data. In particular, indices
have to be sorted. There's a warning about this on the doc comments for
both types (on the constructors you're using....)

**Comment by stucchio** [comment]
It might be worthwhile to run a check on the index array to make sure it's actually sorted? Maybe put this into the body of `SparseVector`?

```
  cfor(0)(i => i < index.size, i => i+1)(i => {
    if ((i > 0) && (index(i) < index(i-1))) {
      throw new IllegalArgumentException("The index array must be sorted, but your array is decreasing from position " + (i-1) + " to position " + i)
    }
  })
```

**Comment by dlwh** [comment]
The spark people objected, because performance. It might be worth having a
flag that has to be suppressed.

**Comment by asevans48** [comment]
Ok I will look now. Thanks

**Comment by dlwh** [comment]
there are other friendlier constructors (some on the companion object) or other creation methods, e.g. VectorBuilder and CSCMatrix.Builder

**Comment by asevans48** [comment]
Thanks. sorry about that.

**Comment by dlwh** [comment]
no worries! we should probably make it safe by default, with a performance escape hatch.
