### ISSUE TITLE
Support for approxEqual

### ISSUE THREAD

**Issue by adgaudio** [scalanlp/breeze#501]
Hi!

As far as I can tell, it seems like we cannot currently evaluate if two `DenseMatrix` instances are approximately equal without stepping through some extra hoops.  For instance:

```
scala> val a = accumulate(DenseVector(1/5D, 2/5D, 3/5D))
a: breeze.linalg.DenseVector[Double] = DenseVector(0.2, 0.6000000000000001, 1.2000000000000002)

scala> a == DenseVector(0.2D, 0.6D, 1.2D)
res9: Boolean = false
```

It would seem to me that this should return true, or we should be able to do something like:

```
a approxEquals(1e-6) DenseVector(0.2D, 0.6D, 1.2D)
or
a approxEquals DenseVector(0.2D, 0.6D, 1.2D)
or 
a === DenseVector(0.2D, 0.6D, 1.2D)
```

I would be happy to submit a PR to add an approximate equal method or otherwise address this issue if approximate equality testing isn't already supported, but I'd need a bit of guidance on the best way to implement it.

**Comment by adgaudio** [comment]
bump

I plan to close this issue in a couple days if there are no comments, as I'm assuming that means there is not enough interest for it.

**Comment by dlwh** [comment]
bleh sorry, missed it.

Breeze has breeze.linalg.isClose(dv1, dv2[, optional tolerance]) already.
I'd be on board with adding a =~= or ≈ operator or something like it.

**Comment by adgaudio** [comment]
Ah thank you for this!  Rather than add a redundant operator, I'll added isClose to the wiki documentation:  "Reduction UFuncs" page in https://github.com/scalanlp/breeze/wiki/Universal-Functions.

**Comment by adgaudio** [comment]
In case it's helpful to anyone in the future, I found that there is a `closeTo` for Doubles defined in a couple places

 [source code](https://github.com/scalanlp/breeze/blob/f4c326f9f219859156a8c55bc667369813fa4b52/math/src/main/scala/breeze/util/Implicits.scala#L43) for a rich double implicit:

```
import breeze.util.Implicits._
1D.closeTo(1.00001)  // --> true
```

[breeze.numerics package](https://github.com/scalanlp/breeze/blob/44a9c4d6c9e591dc90273cc42ba266b0738be72f/math/src/main/scala/breeze/numerics/package.scala#L681) also defines closeTo for double:

```
import breeze.numerics.closeTo
closeTo(1D, 1.00001)
```

**Comment by dlwh** [comment]
lol, probably I should probably pick one
