### ISSUE TITLE
MultivariateGaussian.scala bug. Integer division

### ISSUE THREAD

**Issue by bnoreus** [scalanlp/breeze#508]
On line 54 in MultivariateGaussian.scala it says:

 mean.length/2 * log(2 * Pi) + det

It should say mean.length / 2.0 
Right now, it is doing an integer division. If mean.length is 3 then mean.length/2 will be 1 which in turn will give an error.

**Comment by dlwh** [comment]
yuck, thanks

**Comment by dlwh** [comment]
fixed
