### ISSUE TITLE
Create verbosity flag for optimizers

### ISSUE THREAD

**Issue by rpadams** [scalanlp/breeze#530]
This is a great tool and I'm loving it.  However, the optimizers I've played with really spew INFO messages without an obvious way to turn them off, e.g.,

```
16/04/27 23:41:16 INFO SpectralProjectedGradient: Step Size: 0.5000
16/04/27 23:41:16 INFO SpectralProjectedGradient: Val and Grad Norm: 731.034 (rel: 5.48e-05) 936.766
16/04/27 23:41:16 INFO SpectralProjectedGradient: Step Size: 0.5000
16/04/27 23:41:16 INFO SpectralProjectedGradient: Val and Grad Norm: 731.023 (rel: 1.44e-05) 933.997
16/04/27 23:41:16 INFO SpectralProjectedGradient: Step Size: 0.5000
16/04/27 23:41:16 INFO SpectralProjectedGradient: Val and Grad Norm: 731.019 (rel: 5.88e-06) 936.069
16/04/27 23:41:16 INFO SpectralProjectedGradient: Step Size: 0.5000
16/04/27 23:41:16 INFO SpectralProjectedGradient: Val and Grad Norm: 731.015 (rel: 5.89e-06) 937.558
16/04/27 23:41:16 INFO SpectralProjectedGradient: Step Size: 0.5000
16/04/27 23:41:16 INFO SpectralProjectedGradient: Val and Grad Norm: 731.012 (rel: 4.22e-06) 939.727
16/04/27 23:41:16 INFO SpectralProjectedGradient: Step Size: 0.5000
16/04/27 23:41:16 INFO SpectralProjectedGradient: Val and Grad Norm: 731.009 (rel: 3.80e-06) 940.748
16/04/27 23:41:16 INFO SpectralProjectedGradient: Step Size: 0.2500
16/04/27 23:41:16 INFO SpectralProjectedGradient: Val and Grad Norm: 731.008 (rel: 7.04e-07) 944.737
16/04/27 23:41:16 INFO SpectralProjectedGradient: Step Size: 0.5000
```

Having a flag in the optimizer would be nice for turning these off.

**Comment by rpadams** [comment]
In the meantime, if there is a straightforward way to turn off these messages (of which there are many per second) in stdout, I'd find the advice helpful.  Thanks!

**Comment by dlwh** [comment]
So LBFGS (like most of Breeze) uses the slf4j library for logging, which
has a number of possible backends (which all have different configuration
languages). And that's the proper way to configure the verbosity.

Can you maybe tell me what other libraries you depend on?

-- David

**Comment by rpadams** [comment]
Thanks for the quick reply!  I'm using it alongside Spark and graphx, although not via mllib.  I'm a novice at this, so the confusing thing was that I actually need to configure log4j and not anything with slf4j, and that I needed to turn off logging for things I wasn't explicitly using (e.g., SpectralProjectedGradient).  For reference, I did

```
import org.apache.log4j.{Logger, Level}
Logger.getLogger("breeze.optimize.ProjectedQuasiNewton").setLevel(Level.WARN)
Logger.getLogger("breeze.optimize.SpectralProjectedGradient").setLevel(Level.WARN)

```

**Comment by dlwh** [comment]
right, slf4j doesn't do any configuration. it just passes things through to
the underlying backend (which is log4j in Spark land)

**Comment by nickresnick** [comment]
I'm coming at this from the other side: I want to turn on DEBUG level logs from breeze. Can you provide the `Logger.getLogger` statement that will get the right logger? I'm running L-BFGS-B in a spark-shell.
