### ISSUE TITLE
CSCMatrix left division error

### ISSUE THREAD

**Issue by Ldpe2G** [scalanlp/breeze#536]
I want to do a sparse matrix left division operation for example:

val A = new CSCMatrix[Float]()
val B = new CSCMatrix[Float]()
val x = A \ B 

but got the following error:

could not find implicit value for parameter op:      breeze.linalg.operators.OpSolveMatrixBy.Impl2[breeze.linalg.CSCMatrix[Float],breeze.linalg.CSCMatrix[Float],That] - not enough arguments for method : (implicit op:breeze.linalg.operators.OpSolveMatrixBy.Impl2[breeze.linalg.CSCMatrix[Float],breeze.linalg.CSCMatrix[Float],That])That. Unspecified value parameter op.

Anyone help? thanks.

**Comment by dlwh** [comment]
try Doubles. Those tend to work better

**Comment by Ldpe2G** [comment]
thanks @dlwh , I tried Double, but got the same error.
