### ISSUE TITLE
Multinomial probabilityOf() indexing is contrintuitive

### ISSUE THREAD

**Issue by kokorins** [scalanlp/breeze#538]
I'm not sure it's an issue. I suppose negative indices for counting from end, still it could be more straightforward to return the vector of normalized probabilities in this case. 

```
import breeze.linalg.DenseVector
import breeze.stats.distributions.Multinomial
import scala.util.Try

val mrnd = Multinomial(DenseVector(0.4, 0.6))

(-3).to(2).foreach(i=>println(s"$i:"+Try(mrnd.probabilityOf(i))))
```

and output is 

```
-3:Failure(java.lang.IndexOutOfBoundsException: -3 not in [-2,2))
-2:Success(0.4)
-1:Success(0.6)
0:Success(0.4)
1:Success(0.6)
2:Failure(java.lang.IndexOutOfBoundsException: 2 not in [-2,2))
```

**Comment by dlwh** [comment]
i guess you want it to throw if it's outside [0, 2) instead?

**Comment by kokorins** [comment]
I suppose that would be not a bad idea, as Multinomial depends on DenseVector apply method. If anyone replaces it with something else (eg SparseVector) the negative indices will throw.
Though I propose to replace the function probabilityOf with just probabilities 
`def probabilities = params/sum`

**Comment by mou7** [comment]
I agree that the behavior is counter-intuitive. 
@kokorins why would you replace the function `probabilityOf` with 
`def probabilities = params/sum`
