### ISSUE TITLE
Setting number of threads in breeze

### ISSUE THREAD

**Issue by luiarthur** [scalanlp/breeze#539]
Hi,

Is there a way to temporarily change the number of threads available for matrix computations involving breeze matrices / vectors? (They're done using openblas, right?) For instance, when using openblas in C++, you can temporarily change the number of threads that openblas subroutines use by `openblas_set_num_threads(1);`. Is there an equivalent in breeze? I want to do something _like:_

``` scala
val Xs = (1 to 1000).map( x => DenseMatrix.rand(200,200) )
Xs.toList.par.foreach( x => x.t * x )
```

Here `x.t *x` uses all cores on my machine. It would be nice if the matrix computations here would use 1 thread (instead of all) so I can use the threads to get the 1000 `x.t * x` 's in parallel.

**Comment by dlwh** [comment]
nope. We outsource to netlib java (which just calls out to whatever blas
impl is lying around). You might check there.

**Comment by luiarthur** [comment]
Great, thanks.
