### ISSUE TITLE
Problems with toString for DenseMatrix

### ISSUE THREAD

**Issue by CC007** [scalanlp/breeze#544]
I created a DenseMatrix[Double] object. It behaves properly apart from one thing. When I try to execute the toString method, I get the following error:

`java.lang.NoSuchMethodError: scala.collection.immutable.Range.validateRangeBoundaries(Lscala/Function1;)Z`

When I debug, the debugger also throws an error for the matrix value:

`Method threw 'java.lang.NoSuchMethodError' exception. Cannot evaluate breeze.linalg.DenseMatrix$mcD$sp.toString()`

In the debugger and from my code I am still able to see and use the matrix contents.

Scala version: scala-library v2.11.7 / v2.11.8
breeze math version: breeze-math_2.10 v0.4

**Comment by dlwh** [comment]
You're using a breeze that's incompatible with Scala 2.11, and it's also a
very old breeze. Please use breeze-math_2.11, and probably v 0.12

**Comment by CC007** [comment]
mvnrepository doesn't have that version yet. Is could the 2.11 version be made available there? And in the mean time, what repo already has the 2.11 version?

**Comment by dlwh** [comment]
err right, this one:
http://mvnrepository.com/artifact/org.scalanlp/breeze_2.11/0.12

**Comment by CC007** [comment]
ok, that could work for now, but I'd prefer there to be a math specific dependency in the future. Any info on when that is gonna be released?
