### ISSUE TITLE
BitVector's method mapActivePairs touches zero entries.

### ISSUE THREAD

**Issue by chuan92** [scalanlp/breeze#545]
I'm not sure if this is a bug in the BitVector class.

``` scala
import breeze.linalg._
val a = BitVector(10)(1,3,5,7)

//the following two lines return the same result...
a.mapActivePairs((k,v)=>k)
a.mapPairs((k,v)=>k)
```

version: breeze_2.11:0.11.2

**Comment by dlwh** [comment]
in general the contract with mapActive is that it might skip zeros, but it
doesn't have to. We should probably fix BitVector though
