### ISSUE TITLE
#Get error when use LBFGS

### ISSUE THREAD

**Issue by universewill** [scalanlp/breeze#546]
# The error is as follow:

16/04/19 18:47:35 ERROR LBFGS: Failure! Resetting history: breeze.optimize.FirstOrderException: Line search zoom failed
16/04/19 18:49:18 ERROR LBFGS: Failure again! Giving up and returning. Maybe the objective is just poorly behaved?

---

And also i notice that there is a LBFGS-B implementation. What's the difference between LBFGS and LBFGS-B?
Is ProjectedQuasiNewton optimizer more efficient and powerful than LBFGS and LBFGS-B?

**Comment by dlwh** [comment]
most likely your gradient is wrong or the convergence tolerance is set too
tightly.

LBFGS-B is a bit buggy, but it accepts box constraints to enforce that all
elements of the vector are between some bounds.

ProjectedQuasiNewton can handle (nearly) all convex constraints, but
requires a projection function to take a vector and put it back in the set

**Comment by PayneJoe** [comment]
I also encountered this problem ,  and I tried few times adjusting he convergence tolerance , unfortunately it did not work . Can you explain in detail why and how the gradient is wrong ？Much appreciated for that -)
