### ISSUE TITLE
stats.distributions.Rand not serializable

### ISSUE THREAD

**Issue by matt-gardner** [scalanlp/breeze#552]
Is there some reason that this class isn't easily serializable?  If not, it would be nice to make this serializable, so I can, e.g., efficiently sample from a multinomial in spark.

I tried doing this myself, but got an error about there being no default constructor, and I'm not familiar enough with specialized traits and whatnot to be confident about fixing this correctly.

**Comment by dlwh** [comment]
no reason. I'll add it now.
