### ISSUE TITLE
Rounding error in MultivariateGaussian logNormalizer

### ISSUE THREAD

**Issue by ghost** [scalanlp/breeze#554]
Hello Breeze world,
I enjoy using your framework, however I stumbled upon a numeric rounding error in the MultivariateGaussian logNormalizer computation, which is computed with
`mean.length/2.0 *  log(2 * Pi) + det`

Assume a multivariate Gaussian of length 3 with the identify matrix as the covariance matrix.
The current implementation yields the result: 1.837...
whereas the same code in matlab suggest a factor of 2.75...

I suspect it is because of a rounding error in the division, because
`mean.length.toDouble / 2.0 *  log(2 * Pi) + get`
would yield the same result. Would someone please fix that?

**Comment by dlwh** [comment]
hrm, can you give me the matlab code you run?

**Comment by a-geissler** [comment]
I have further researched the issue. With commit 327a745cb7a6565fdab3b126d7156ae70ce5451a (March) the issue was resolved:
```
-    mean.length/2 *  log(2 * Pi) + get
 +    mean.length/2.0 *  log(2 * Pi) + get
```
However, the current breeze version 0.12 does not contain that update yet.
