### ISSUE TITLE
covariance?

### ISSUE THREAD

**Issue by devinshields** [scalanlp/breeze#555]
Hello!
I'm hoping to usg breeze in some kernel density estimation work, but part of the [KDE bandwidth selection subroutine](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html) uses a covariance matrix, which is currently unavailable in breeze.

I'm not the first person to inquire about covariance:
https://groups.google.com/forum/#!topic/scala-breeze/fMsAQvHFkMs

and it looks like some core covariance functionality is already available in the apache commons math libraries:
http://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math3/stat/correlation/Covariance.html

Can you add covariance? Or point me towards the contributor guidelines?

Thanks!

**Comment by DonBeo** [comment]
I can write a covariance function but I need to understand where. I think the best would be to make a file "statistical moments" that contains the functions to compute the 6 statistical moments https://en.wikipedia.org/wiki/Moment_(mathematics)#Mean

**Comment by DonBeo** [comment]
I think covariance is actually already available

```
"covmat should produce correct values for matrix" in {
      val d = DenseMatrix((1.0,2.0), (2.0, -3.0),(3.0, 4.0), (4.0, 5.0))
      val result: DenseMatrix[Double] = covmat(d)
      assert( math.abs( result(0,1) - 2.66666667) < 1e-7)
      assert( math.abs( result(1,0) - 2.66666667) < 1e-7)
      assert( math.abs( result(0,0) - 1.66666667) < 1e-7)
      assert( math.abs( result(1,1) - 12.66666667) < 1e-7)
    }

```
