### ISSUE TITLE
Broadcast with Custom Binary UFunc

### ISSUE THREAD

**Issue by NoahMarconi** [scalanlp/breeze#560]
I'm working on a user defined binary UFunc and see a quick how-to on the google groups page (https://groups.google.com/forum/#!searchin/scala-breeze/binary$20ufunc/scala-breeze/OTlDf_IItgY/u2hBNFlzDQAJ)

``` scala
val f = UFunc(math.pow _)
val m = DenseMatrix((1.0,2.0,3.0), (4.0,5.0,6.0))
```

Works great when comparing two DenseVectors:

``` scala
f(m(::, 0), m(::, 1))
res38: breeze.linalg.DenseVector[Double] = DenseVector(1.0, 1024.0)
```

However, I hit an error when trying to broadcast:

``` scala
f(m(::, *), m(::, 1))
<console>:18: error: could not find implicit value for parameter impl: breeze.generic.UFunc.UImpl3[breeze.generic.WrappedUFunc.type,breeze.generic.WrappedUFunc2[Double,Double,Double],breeze.linalg.BroadcastedColumns[breeze.linalg.DenseMatrix[Double],breeze.linalg.DenseVector[Double]],breeze.linalg.DenseVector[Double],VR]
              f(m(::, *), m(::, 1))
```

Is there something I'm missing to enable broadcasting?

**Comment by dlwh** [comment]
no, i think that's just a limitation in how broadcasting works right now.
i'll try to look into it (though I'm pretty swamped right now so can't
promise a timeline)

I am a bit surprised it doesn't work, but only a bit.

**Comment by NoahMarconi** [comment]
Thanks! 

In case it comes up for others, I have a workaround in the meantime for my particular use case by partially applying the UFunc and then mapping the broadcasted columns instead:

```{scala}
val p = f(m(::, 1), _:breeze.linalg.DenseVector[Double])

m(::, *).map(p)
res55: breeze.linalg.DenseMatrix[Double] =
2.0    4.0     8.0
625.0  3125.0  15625.0
```

**Comment by dlwh** [comment]
well that took forever to get to. I have a stupid kludge rather than a principled fix.
