### ISSUE TITLE
Iterator to DenseVector without Array?

### ISSUE THREAD

**Issue by gkthiruvathukal** [scalanlp/breeze#568]
Hi, I'm using Breeze in a project. Is there any way to go straight from an iterator to DenseVector without creating a Scala Array first? I'm not trying to cut out the middle man (person) but if there is a way, I'd like to do it.

In my current code, I am able to get a DenseVector from an iterator. But I first need to do either Array(iter) or iter.toArray prior to creating a DenseVector. This is a bit inefficient, because I am working with rather large array structures (for benchmarking purposes). Or does DenseVector just use the incoming Array as its underlying representation? From what I can tell by casually studying your source code, I don't think this is the case.

I'm potentially interested to work on support for this, but it seems like a far-reaching change that would be important to all things Tensor and various sparse representations. But I want to make sure there isn't a design reason that this was omitted from Breeze's design in the first place.

**Comment by dlwh** [comment]
breeze densevectors (and most of Breeze) operates on Arrays exclusively
right now. It would be a large change to support Iterators, in particular
