### ISSUE TITLE
breeze DenseMatrix multiplication * methods get errors

### ISSUE THREAD

**Issue by a1300787** [scalanlp/breeze#570]
I am a freshman in scala language. Today, I want use breeze to solve a matrix problem. This is my code block:

 val Matrix=breeze.linalg.csvread(new File(inpath))
    //read a matrix from outside file then the pattern of the Matrix variable is (DenseMatrix[Double])

 val block=dataT(::,start_index until  end_index) 
   //dataT just was a matrix return from the code of line 1 ,and block was a column slicing of dataT , we could see it pattern still same as Matrix 

 val ab = data* block  //get error,  the pattern of ab become a nothing!! Why??

I just want to implement a matrix-matrix multiplication. I don't understand why it won't work. Anyway I can bring out still can't solve the problem. Thanks

**Comment by a1300787** [comment]
the data in val ab=data*block  equal  the Matrix

**Comment by dlwh** [comment]
can you paste an actual example that you tried?

my guess is that it actually compiles fine, but your IDE is confused by
Breeze (this happens a lot)

**Comment by a1300787** [comment]
Thanks @dlwh   I use IntelliJ IDEA with  the windows environment ,

**Comment by a1300787** [comment]
`def loadMSIData(sc:SparkContext,inpath:String,nparts:Int)={
val Matrix=breeze.linalg.csvread(new File(inpath))
  Matrix
}

val data = loadMSIData(sc, inpath, nparts = block_size) // load 3x3 Matrix
val n = data.rows
val num_iter = ceil(n / block_size)

val A =BDM(n,n)
val dataT=data.t  //transpose data
val a= BDV(sum(data:*data,Axis._1).toArray) //sum all rows elements
var aa=a * BDV.fill(3){1.0}.t   // column vector * a row vector with full 1

  val block=dataT(::,0 until  3)  // column slicing dataT 
    aa=aa(::,0 until 3 )   // same 
  val b=BDV(sum(block:*block,Axis._0).toArray) 
  val bb=(b *BDV.fill(3){1.0}.t).t
val ab = data * block   //get error, the data and block have same pattern
val dist=aa+bb-2*ab    // won't work`

this is my code bolck. Thanks for you patience!

**Comment by dlwh** [comment]
This compiles fine for me in actual scala. You can't trust intellij. it gets it wrong a lot. (Just run build). I did have to change `2 * ab` to `2.0 * ab` because Breeze can't do int to double promotion


```scala
def foo = {
val block_size = 5

val data = DenseMatrix.rand(10, 15)
val n = data.rows
val num_iter = ceil(n / block_size)

val A = DenseMatrix.zeros[Double](n,n)
val dataT=data.t  //transpose data
val a= DenseVector(sum(data:*data,Axis._1).toArray) //sum all rows elements
var aa=a * DenseVector.fill(3){1.0}.t   // column vector * a row vector with full 1

  val block=dataT(::,0 until  3)  // column slicing dataT 
    aa=aa(::,0 until 3 )   // same 
  val b = DenseVector(sum(block:*block,Axis._0).t.toArray) 
  val bb=(b * DenseVector.fill(3){1.0}.t).t
val ab = data * block   
val dist=aa+bb- 2.0 * ab    // won't work
}
```

**Comment by a1300787** [comment]
@dlwh    Thanks ,  I will try again .  OK  please let me close the Q
