### ISSUE TITLE
Big Matrix issue

### ISSUE THREAD

**Issue by a1300787** [scalanlp/breeze#574]
Hi!
  recently， I want create a Big Square  Matrix which the size is n*n  and n bigger than 100000.
but I got a exception :  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0

 The test code like this ：
 `val aaa=DenseMatrix.ones[Double](111740,111740) `
`println(aaa)`

 when I tracking source code , I found the size of the Array within DenseMatrix was't enough to support  

What can i do if I want use big matrix in the cluster?. 

Thanks

**Comment by EvanOman** [comment]
Not sure why you are getting this error specifically, but you asking your system to store `100,000*100,000` doubles. Each double is at least `8` bytes so you are trying to put 

```
8 * 100,000 * 100,000 = 80000000000 bytes = 80 gigabytes
```

So unless your system (or the node in your cluster?) has 80 GB of RAM to work with, something is going to break.
