### ISSUE TITLE
About Boolean Operators

### ISSUE THREAD

**Issue by universewill** [scalanlp/breeze#578]
I use the boolean operator, but it seems that the return type is "Nothing"
For example, type of s is "Nothing" in the code below:
---
    val s = x :& w
    s

**Comment by dlwh** [comment]
your IDE is probably just confused. try compiling it

**Comment by universewill** [comment]
ok, my ide is IntelliJ IDEA ...

**Comment by dlwh** [comment]
yeah, intellij gets confused frequently
