### ISSUE TITLE
Build Spark with breeze failed

### ISSUE THREAD

**Issue by apollos** [scalanlp/breeze#581]
I add the breeze as dependecy in pom.xml of top directory and the mllib/pom.xml.
<dependency>
      <groupId>org.scalanlp</groupId>
      <artifactId>breeze_2.11</artifactId> 
      <version>0.12</version>
    </dependency>

But I get the followed error, is it a error configuration or incompatible version or other issues?

[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ spark-mllib_2.10 ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spark-mllib_2.10 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ spark-mllib_2.10 ---
[INFO] Using zinc server for incremental compilation
[info] Compiling 238 Scala sources and 4 Java sources to /home/yu/workspace/spark/mllib/target/scala-2.10/classes...
[error] /home/yu/workspace/spark/mllib/src/main/scala/org/apache/spark/mllib/clustering/LDAOptimizer.scala:487: type mismatch;
[error]  found   : breeze.linalg.Transpose[breeze.linalg.DenseVector[Double]]
[error]  required: breeze.linalg.DenseMatrix[Double]
[error]     val logphat: BDM[Double] = sum(LDAUtils.dirichletExpectation(gammat)(::, breeze.linalg.*)) / N
[error]                                                                                                ^
[error] one error found
[error] Compile failed at Sep 12, 2016 11:12:22 PM [11.840s]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:

**Comment by dlwh** [comment]
I changed how that works a year ago or so. change the type to
DenseVector[T] (or BDV) and use .t after the close parens

**Comment by apollos** [comment]
I am newbie. The error code is at line 487, how shall I fix it?

483   private def updateAlpha(gammat: BDM[Double]): Unit = {
484     val weight = rho()
485     val N = gammat.rows.toDouble
486     val alpha = this.alpha.toBreeze.toDenseVector
487     val logphat: BDM[Double] = sum(LDAUtils.dirichletExpectation(gammat)(::, breeze.linalg.*)) / N
488     val gradf = N * (-LDAUtils.dirichletExpectation(alpha) + logphat.toDenseVector)
489

**Comment by dlwh** [comment]
sure:

val logphat: BDV[Double] = sum(LDAUtils.dirichletExpectation(gammat)(::,
breeze.linalg.*)).t / N

if BDV doesn't work, use breeze.linalg.DenseVector

**Comment by apollos** [comment]
Thanks very much. It works well and performance is very good. Thanks a lot.
