### ISSUE TITLE
Implementation for multiplication between scalar and sparse vector is missing

### ISSUE THREAD

**Issue by jyuhuan** [scalanlp/breeze#584]
The following example tries to multiply a scalar number of type `Double` with a `SparseVector[(Int, Double)]`:

``` scala
val a = SparseVector(3 -> 1.0, 6 -> 2.0, 9 -> 3.0)
val b = 5.0 * a
```

The code fails to compile because

> Error: could not find implicit value for parameter op: breeze.linalg.operators.OpMulMatrix.Impl2[Double,breeze.linalg.SparseVector[(Int, Double)],That]
>   val b = 5.0 \* a

It seems that the implicit implementation for such type of multiplication is missing. 

However, if we were to do the same thing on a `DenseVector[Double]`, everything is fine:

``` scala
val a = DenseVector(1.0, 2.0, 3.0)
val b = 5.0 * a
```

The only thing imported for both cases was

``` scala
import breeze.linalg._
```

Have I missed a package I should import for the sparse case?

**Comment by dlwh** [comment]
So, what's wrong is that you are create a vector of pairs. The SparseVector
constructor you want is SparseVector(length)(pairs) (otherwise, how does
the sparse vector know how long the vector should be?)

**Comment by jyuhuan** [comment]
Do you mean the following?
```scala
val a = SparseVector(10)(3 -> 1.0, 6 -> 2.0, 9 -> 3.0)
val b = 5.0 * a
```

The code above still fails to find the implicit `op`.

Even if I get rid of the pairs, as shown below, the problem still exists.
```scala
val a = SparseVector.zeros[Double](5)
val b = 5.0 * a
```

**Comment by jyuhuan** [comment]
I see. Thanks for the quick replies!
