### ISSUE TITLE
Missing implementation for elementwise multiplication of DenseVector[Complex] and DenseVector[Double]?

### ISSUE THREAD

**Issue by johnPertoft** [scalanlp/breeze#585]
As the headline says, can't multiply DenseVectors of Complex and Double types respectively.

**Comment by dlwh** [comment]
breeze basically never supports vectorized crosstype operations. you're
best off converting the doubles to Complexes

**Comment by johnPertoft** [comment]
Ok, thanks for answering. Is there a reason for it?

**Comment by dlwh** [comment]
breeze relies heavily on code generation to get efficiency, and generating
quadratically many classes for operators is expensive
