### ISSUE TITLE
tests failing in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [scalanlp/breeze#587]
```
[breeze] [error] Failed tests:
[breeze] [error]    breeze.linalg.DenseMatrixTest
[breeze] [error]    breeze.optimize.ProjectedQuasiNewtonTest
[breeze] [error]    breeze.linalg.DenseVectorTest
```

from https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/645/console

**Comment by dlwh** [comment]
That's a bit terrifying.I'll look tonight or tomorrow. Thanks for the heads
up!

**Comment by SethTisue** [comment]
for additional community build friendliness, I'd suggest you upgrade to ScalaTest 3.0, [remove this unused import](https://github.com/SethTisue/breeze/commit/6647d9a74621d0f6dcf3d4ed2ce48a226137d58b), and [update this version-checking logic for 2.12](https://github.com/SethTisue/breeze/commit/a0cdb8e16b53428165b53080a916a74013bb032a). note the latter commit probably isn't suitable as is, you'll probably need to move a newer Shapeless version that's available for 2.12.0-RC1

**Comment by dlwh** [comment]
Hi @SethTisue, thanks again for the help.

what's the deal with shapeless right now? My understanding (from both
mvnrepository.com and from http://www.scala-lang.org/news/2.12.0-RC1) is
that it's not published for RC1. Is there a good easy way for me to get
good-enough Shapeless without going through the community build thing?

**Comment by SethTisue** [comment]
oh right, I forgot :-(

I think some of your other dependencies:

```
[info] Project breeze
[info]   depends on: discipline, machinist, macro-compat, macro-paradise, scala, scala-logging, scala-parser-combinators, scalacheck, scalatest, scalaz, scalaz-stream, scodec-bits, scoverage, shapeless, specs2_24, spire
```

aren't published for 2.12 yet either, e.g. Spire. so in practice, the community build is the only you can reasonably test this right now. it's runnable locally, instructions at https://github.com/scala/community-builds/wiki/Maintenance#how-do-i-run-it-locally. your first run will take hours and testing incremental changes will take 5–10 minutes or so each time, so it's a slow way to work.

**Comment by dlwh** [comment]
Ok cool. I'll make the other changes you outlined for sure (and do some
needed housekeeping i've been putting off), and I may or may not wait for
RC2, depending on how much pain is involved/what I think the bug is. (I
really hope it's not a bug in specialization...)

**Comment by dlwh** [comment]
blah, I'm hitting

```
::::::::::::::::::::::::::::::::::::::::::::::

::          UNRESOLVED DEPENDENCIES         ::

::::::::::::::::::::::::::::::::::::::::::::::

:: com.typesafe.akka#akka-actor;2.0.5: not found

::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by dlwh** [comment]
(the breeze bug seems to be that scalacheck has gotten much more tricksy
with the edge cases it generates)

**Comment by SethTisue** [comment]
> :: com.typesafe.akka#akka-actor;2.0.5: not found

try 2.4.10

**Comment by dlwh** [comment]
ok, updated to latest scalacheck and stabilized a whole lot of tests. i
didn't end up trying it in community

**Comment by SethTisue** [comment]
let's try it: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/666/consoleFull (404 for now, jobs ahead in queue)

**Comment by SethTisue** [comment]
the same tests are failing

**Comment by dlwh** [comment]
blah, ok, i'll see what i can do.

**Comment by SethTisue** [comment]
fyi @dlwh @tixxit @non @johnynek

**Comment by SethTisue** [comment]
I have not seen any failures lately, so let's assume it's fine
