### ISSUE TITLE
"i is already defined as value i" When trying to modify element of DenseVector

### ISSUE THREAD

**Issue by michaellindon** [scalanlp/breeze#594]
I'm using Intellijidea

```
val i=0
val Bcopy=B
val Bcopy(i)=1
```
B is a DenseVector[Double]. I am trying to make a copy of it and then modify one of the elements. When I try to compile this I get an error

```
Error:(61,16) i is already defined as value i
                     lazy val Bcopy(i)=1
```

Is this an intellijidea specific problem or is this the expected the behaviour? If so, how am I supposed to modify an element of the vector?

**Comment by EvanOman** [comment]
This is a language level problem: you don't use the `val` keyword when reassigning a value in a collection:

```{scala}
scala> val a = DenseVector.range(0,5)
a: breeze.linalg.DenseVector[Int] = DenseVector(0, 1, 2, 3, 4)

scala> val b = a.copy
b: breeze.linalg.DenseVector[Int] = DenseVector(0, 1, 2, 3, 4)

scala> 

scala> b(0) = 1

scala> b
res5: breeze.linalg.DenseVector[Int] = DenseVector(1, 1, 2, 3, 4)
```

**Comment by michaellindon** [comment]
Thanks, but I'm still getting weird errors when trying to access an element by an integer index i. Please see the highlighted text in the attachment and the error at the bottom
![screenshot from 2016-10-08 19-53-38](https://cloud.githubusercontent.com/assets/4892846/19216608/2104a77c-8d91-11e6-9ce3-e05c0b1e8444.png)

**Comment by michaellindon** [comment]
ok i found i should use the update method
