### ISSUE TITLE
SBT fails: module is not authorized to depend on itself

### ISSUE THREAD

**Issue by carschno** [scalanlp/breeze#596]
I am trying to compile the Breeze master branch on my Ubuntu 16.04 system, with SBT 0.13.7. `sbt compile` fails with the following error message:

```
[error] (math/*:update) java.lang.IllegalArgumentException: a module is not authorized to depend on itself: org.scalanlp#breeze_2.11;0.12
```

The same error is also shown when I try to compile in the Intellij IDE, using SBT, except that it additionally reported for the other modules (math, benchmark, natives, math, root, viz).

**Comment by dlwh** [comment]
that's a pretty old version of sbt, please update and let me know if it
still fails

**Comment by carschno** [comment]
After updating to SBT v0.13.12, the problem persists. Here's a more verbose output.

    > compile
    [warn] Credentials file /home/XXX/.ivy2/.credentials does not exist
    [info] Updating {file:/home/XXX/git/breeze/}macros...
    [warn] Credentials file /home/XXX/.ivy2/.credentials does not exist
    [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
    [warn]  * org.scalacheck:scalacheck_2.11:(1.11.3, 1.13.2)
    [warn]  * org.scalatest:scalatest_2.11:(2.1.3, 3.0.0)
    [info] Resolving org.scalanlp#breeze_2.11;0.12 ...
    [warn] circular dependency found: org.scalanlp#breeze-macros_2.11;0.13-0b7934934f935389e3356ea643cd00c294c8e073-SNAPSHOT->org.scalanlp#breeze_2.11;0.12->org.scalanlp#breeze-macros_2.11;0.12
    [info] Resolving jline#jline;2.12.1 ...
    [info] Done updating.
    [warn] Credentials file /home/XXX/.ivy2/.credentials does not exist
    [warn] Credentials file /home/XXX/.ivy2/.credentials does not exist
    [warn] Credentials file /home/XXX/.ivy2/.credentials does not exist
    [info] Updating {file:/home/XXX/git/breeze/}math...
    [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
    [warn]  * org.scalacheck:scalacheck_2.11:(1.11.3, 1.13.2)
    [warn]  * org.scalatest:scalatest_2.11:(2.1.3, 3.0.0)
    [warn]  * org.spire-math:spire_2.11:(0.7.4, 0.12.0)
    [error] a module is not authorized to depend on itself: org.scalanlp#breeze_2.11;0.12
    [info] Compiling 3 Scala sources to /home/XXX/git/breeze/macros/target/scala-2.11/classes...
    [...]
    [error] (math/*:update) java.lang.IllegalArgumentException: a module is not authorized to depend on itself: org.scalanlp#breeze_2.11;0.12

**Comment by carschno** [comment]
When running `update` with debug enabled, I get numerous output lines like the following, indicating that the `macros` module indeed depends on the parent project:

    [debug] == resolving dependencies org.scalanlp#breeze-macros_2.11;0.13-0b7934934f935389e3356ea643cd00c294c8e073-SNAPSHOT->org.scalanlp#breeze_2.11;0.12 [compile->default(compile)]

I suppose this is the root cause for the compile failure, but I haven't been able to nail down where that (transitive?) dependency comes from.

**Comment by carschno** [comment]
Any more hints on this? I'm using the master branch, SBT 0.13.13 and Scala 2.11.7 (although the right version should be pulled by SBT). I wonder whether I am the only one with that issue.

**Comment by wsargent** [comment]
I ran into this -- I had two different subprojects, but I had copied and pasted the name incorrectly:

```
lazy val logging = (project in file("logging")).settings(
  name = "logging",
 version      := "0.1.0-SNAPSHOT"
)

lazy val logstash = (project in file("logstash")).settings(
  name = "logging",
  version := "0.1.0-SNAPSHOT"
).dependsOn(logging)
```

Once I took out the "name = logging" bit it worked fine.
