### ISSUE TITLE
Large-sale DenseMatrix creation

### ISSUE THREAD

**Issue by drandreyoon** [scalanlp/breeze#597]
I am trying to create a square matrix with the dimensions of (n x n), where n is 50000 or greater using DenseMatrix in Breeze. When I create it in the following way,  I ran into the array index out of bounds  exception below, 

``` scala
scala> import breeze.linalg.DenseMatrix
scala> val matrix = DenseMatrix.ones[Float](50000,50000)
```

> java.lang.ArrayIndexOutOfBoundsException: 0
>   at breeze.linalg.DenseMatrix$mcF$sp.apply$mcF$sp(DenseMatrix.scala:87)
>   at breeze.linalg.DenseMatrix$mcF$sp.apply(DenseMatrix.scala:82)
>   at breeze.linalg.DenseMatrix$mcF$sp.apply(DenseMatrix.scala:53)
>   at breeze.linalg.Matrix$$anonfun$colWidth$1$1.apply$mcII$sp(Matrix.scala:71)
>   at breeze.linalg.Matrix$$anonfun$colWidth$1$1.apply(Matrix.scala:71)
>   at breeze.linalg.Matrix$$anonfun$colWidth$1$1.apply(Matrix.scala:71)
>   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
>   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
>   at scala.collection.immutable.Range.foreach(Range.scala:160)
>   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
>   at scala.collection.AbstractTraversable.map(Traversable.scala:104)
>   at breeze.linalg.Matrix$class.colWidth$1(Matrix.scala:71)
>   at breeze.linalg.Matrix$class.toString(Matrix.scala:76)
>   at breeze.linalg.DenseMatrix.toString(DenseMatrix.scala:53)
>   at breeze.linalg.Matrix$class.toString(Matrix.scala:122)
>   at breeze.linalg.DenseMatrix.toString(DenseMatrix.scala:53)
>   at scala.runtime.ScalaRunTime$.scala$runtime$ScalaRunTime$$inner$1(ScalaRunTime.scala:332)
>   at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:337)
>   at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:345)
>   at .$print$lzycompute(<console>:10)
>   at .$print(<console>:6)
>   at $print(<console>)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
>   at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
>   at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
>   at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
>   at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
>   at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
>   at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
>   at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
>   at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
>   at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
>   at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
>   at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
>   at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
>   at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
>   at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
>   at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
>   at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
>   at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
>   at org.apache.spark.repl.Main$.doMain(Main.scala:68)
>   at org.apache.spark.repl.Main$.main(Main.scala:51)
>   at org.apache.spark.repl.Main.main(Main.scala)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
>   at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
>   at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
>   at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
>   at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Somehow, it works for n = 70000 (for n less than 50000 as well). Is there a limit in DenseMatrix size, or have I missed something? I am using scala 2.11.8. 

``` scala
scala> val matrix = DenseMatrix.ones[Float](70000,70000)
```

> matrix: breeze.linalg.DenseMatrix[Float] =
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ... (70000 total)
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...
> 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1...`

**Comment by dlwh** [comment]
DenseMatrices are backed by a single java array, which means you can have
at most Integer.MAX_VALUE - 5 (almost but not quite 2^31) elements, so the
largest a square matrix can be is about 46340...

**Comment by drandreyoon** [comment]
I see, that was the problem. Thanks for pointing out!
