### ISSUE TITLE
Bump to Scala 2.12.1

### ISSUE THREAD

**Issue by 3tty0n** [scalanlp/breeze#604]
Scala 2.12.0 is now available.

http://www.scala-lang.org/news/2.12.0

**Comment by dlwh** [comment]
blocked on dependencies (at least https://github.com/non/spire/issues/596)

**Comment by 3tty0n** [comment]
Spire for Scala 2.12.0 is released now.

https://github.com/non/spire/pull/606

**Comment by kamilkloch** [comment]
Any plans for a release for 2.12? :)

**Comment by 3tty0n** [comment]
I will send PR that supports scala 2.12.0

**Comment by mgzuber** [comment]
Any chance on this getting resolved soon?

**Comment by bmckown** [comment]
+1

**Comment by dlwh** [comment]
Hi everyone. Sorry I've been negligent. I'll get to this over the holiday.

**Comment by 3tty0n** [comment]
Hi.

https://github.com/scalanlp/breeze/pull/611 was merged as before.

So, it will be supported for 2.12 soon.

**Comment by kamilkloch** [comment]
Any chance for the 2.12 maven release ?

**Comment by radium226** [comment]
Hello! Is there any update on this issue? Thanks!

**Comment by dlwh** [comment]
http://repo1.maven.org/maven2/org/scalanlp/breeze_2.12/0.13/
