### ISSUE TITLE
Some matrix operations do not work on SliceMatrix

### ISSUE THREAD

**Issue by engelen** [scalanlp/breeze#605]
When slicing a DenseMatrix, not all normal matrix operations that work on DenseMatrix work on SliceMatrix. Example:

```
> val m = DenseMatrix((1,2,3,4),(5,6,7,8),(9,10,11,12))
1  2   3   4   
5  6   7   8   
9  10  11  12
> val indices = List(1,3)
List(1, 3)
> val m_sliced = m(::,indices)
2   4   
6   8   
10  12  
```
Then, trying to calculate the sum of entries for all columns:
```
> sum(m_sliced(::,*))
[error] {file}:19: could not find implicit value for parameter canSlice: breeze.linalg.support.CanSlice2[breeze.linalg.Matrix[Int],collection.immutable.::.type,breeze.linalg.*.type,Result]
[error] 	sum(m_sliced(::,*))
[error] 	            ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 0 s, completed Nov 7, 2016 10:04:29 AM
```

**Comment by PayneJoe** [comment]
I also noticed that a few days ago , we have to convert the sliced matrix into a standard matrix before we do entry accumulation

**Comment by engelen** [comment]
Indeed the calculations work if we convert them to a dense matrix. However, one would expect the entry accumulations to work on the SliceMatrix as they do on the DenseMatrix, as most other operations are available.

For any reader coming here, though, it might be nice to see the solution, so here it is: change the above code to get the dense matrix from the sliced matrix using `toDenseMatrix` on `m_sliced`, and leave the rest of the code intact. The `sum` will now yield a transposed DenseVector. The code is as follows:

```
> val m = DenseMatrix((1,2,3,4),(5,6,7,8),(9,10,11,12))
1  2   3   4   
5  6   7   8   
9  10  11  12
> val indices = List(1,3)
List(1, 3)
> val m_sliced = m(::,indices).toDenseMatrix
2   4   
6   8   
10  12  
> val column_sums = sum(m_sliced(::,*))
Transpose(DenseVector(18, 24))
> column_sums.t
DenseVector(18,24)
```
