### ISSUE TITLE
Tile function not on Wiki

### ISSUE THREAD

**Issue by Joao-M-Almeida** [scalanlp/breeze#606]
The tile function for dense matrices is not mentioned anywhere on the wiki, it should be added there.

I found it by searching the repository and finding the test code: https://github.com/scalanlp/breeze/blob/5fd292608f3152bb0126694f7454890fa47c3e78/math/src/test/scala/breeze/linalg/functions/tileTest.scala

**Comment by dlwh** [comment]
Good point. If you wanted to do it yourself, I'd really appreciate it!

**Comment by Joao-M-Almeida** [comment]
I added it to the wiki on the cheatsheet, I have never used R, so I don't know what is the equivalent and left the R entry empty

**Comment by dlwh** [comment]
thanks!
