### ISSUE TITLE
Covariance Matrix size depends on size of DenseVector[Double] instead of size of Seq[DenseVector[Double]]. Is this a mistake?

### ISSUE THREAD

**Issue by nchinmay** [scalanlp/breeze#607]
Referring to https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/stats/DescriptiveStats.scala#L213
For `breeze.stats.covmat(data: Seq[DenseVector[Double]]): DenseMatrix[Double])`, if `data` has 3 vectors of with 2 elements each, the returned covariance matrix `DenseMatrix[Double]` is of size `2x2`. Shouldn't it be `3x3`?
Basically `val result = new DenseMatrix[Double](firstRow.size, firstRow.size)` should be `val result = new DenseMatrix[Double](data.size, data.size)`

**Comment by dlwh** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/scala-breeze/p3mwa7QBABI/WoumJu7nBgAJ
