### ISSUE TITLE
How to filter selected columns in DenseMatrix ?

### ISSUE THREAD

**Issue by PayneJoe** [scalanlp/breeze#608]
Here is my original DenseMatrix :
1  2  3  4  
5  6  7  8 

I want to get a new matrix filtered some columns, the new matrix like this :
1 3
5 7

How can I achieve that ?

**Comment by dlwh** [comment]
scala> import breeze.linalg._
import breeze.linalg._

scala> val dm = DenseMatrix( (1,2,3,4), (5, 6, 7, 8))
dm: breeze.linalg.DenseMatrix[Int] =
1  2  3  4
5  6  7  8

scala> dm(::, IndexedSeq(0, 2))
res0: breeze.linalg.SliceMatrix[Int,Int,Int] =
1  3
5  7

**Comment by PayneJoe** [comment]
Many thanks , David
