### ISSUE TITLE
New user, example needed: NonlinearMinimizer.scala

### ISSUE THREAD

**Issue by haopan27** [scalanlp/breeze#610]
Hello Daniel:

I couldn't find examples that can teach me how to use this file NonlinearMinimizer.scala under breeze/math/src/main/scala/breeze/optimize/proximal/

The optimization problem I am trying to solve is like the following:

Minimize: y = sum( log( v1 ^ x + v2^ (1-x) ) )
Subject to:
0<x<1

where v1 and v2 are DenseVectors whose values are known. x is the design variable of type Double. I feel NonlinearMinimizer could be of great help here, but don't know where to start. Any input is welcome!

**Comment by debasish83** [comment]
I will work on it...

**Comment by debasish83** [comment]
But the idea is to use a DiffFunction like BFGS and add the cost in...and then put bound proximal...there are bound examples in NonlinearMinimizer but I will add it in wiki....

**Comment by debasish83** [comment]
To unblock:
Define DiffFunction interface for the loss: nlLoss = sum( log( v1 ^ x + v2^ (1-x) ) )

init := 0.0
val nlBox = NonlinearMinimizer(problemSize, BOX, 0.0)
val nlBoxStart = System.nanoTime()
val nlBoxResult = nlBox.minimizeAndReturnState(nlLoss, init)
val nlBoxTime = System.nanoTime() - nlBoxLogisticStart
val nlBoxObj = nlLoss.calculate(nlBoxLogisticResult.x)._1

BOX will construct proximal for 0 <x < 1 but you can put other bounds as well...I will add more details

**Comment by haopan27** [comment]
Thanks so much Debasish! I will keep an eye on the coming updates.

Hao Pan
Data Analytics Engineer
Fractal Industries, Inc.
Office: (703) 995-4199 Ext. 716
Cell: (734) 709-6831

Make everything intelligent.
