### ISSUE TITLE
NotConvergedException.Iterations thrown

### ISSUE THREAD

**Issue by meucaa** [scalanlp/breeze#615]
I am facing an issue and cannot figure out why : can someone explain to me when do a `NotConvergedException` is thrown and especially an `Iterations` one ?

The line throwing the exception is the following : 
`MultivariateGaussian(DenseVector.zeros[Double](N), C).sample(1).head` where N is an `Int` and `C` a covariance matrix. 
What are the conditions on the `C` matrix for this line to run successfully ?

Thank you in advance for your help !

**Comment by dlwh** [comment]
It needs to be positive definite
