### ISSUE TITLE
negative probability !!!

### ISSUE THREAD

**Issue by mou7** [scalanlp/breeze#616]
For the class `breeze.stats.distributions.Gaussian` distribution, evaluating the function `probability(x, y)` yields a negative probability when x > y because we compute it as 

`override def probability(x: Double, y: Double): Double = cdf(y) - cdf(x)`

Is it fine that the function that is supposed to compute a probability yields a negative probability ?

**Comment by dlwh** [comment]
I don't really know what the right behavior is here. Probably the right
answer is 0? because we're getting the probability of an empty range?

**Comment by mou7** [comment]
This is the probability that a Gaussian variable Z is in the interval [x, y]
Pr( x < Z < y) = Pr( Z <  y) - Pr( Z < x), x <= y

This probability is defined if and only if x <= y

If I had to code it I would add a 

'require(x <= y, "The probability is defined only if x < y")'

**Comment by mou7** [comment]
I can make a pull-request if you agree this should change

**Comment by debasish83** [comment]
negative probability may freak out the user...x = y should return 0...but this is the case where x > y...I think a require will be good to guard against it

**Comment by dlwh** [comment]
that would be great, thanks!

**Comment by mou7** [comment]
Voila https://github.com/scalanlp/breeze/pull/617
