### ISSUE TITLE
Error in DescriptiveStats.meanAndVariance?

### ISSUE THREAD

**Issue by apoigne** [scalanlp/breeze#618]
Starting to use the above function the variance results different values as, for instance, variance does in Python. E.g.
```
val mv = breeze.stats.meanAndVariance(DenseVector[Double](1, 2, -3))
mv.variance
```
 yields 7.0 while 
 ```
numpy.var([1, 2, -3]) 
```
yields 4.666666666666667 (which is the same result if I implement Variance according to the Math definition)

Question: is another definition used for variance

If not, playing a bit it seems the value corresponding to python's results is obtained by dividing
```
mv.variance / (mv.count.toDouble / (mv.count -1))
```
which would imply in line 138 of DescriptiveStats 
```
MeanAndVariance(mu, s / (n - 1), n)
```
should be replaced by
```
MeanAndVariance(mu, s / n, n)
```

**Comment by EvanOman** [comment]
This is just the difference between sample standard deviation (what `breeze` is giving you) and population standard deviation (what `numpy` is giving you).

I brought this up in [Issue 553](https://github.com/scalanlp/breeze/issues/553)

**Comment by darrenjw** [comment]
I would argue that Breeze's behaviour is correct (and numpy's is not). R agrees with Breeze:

> var(c(1,2,-3))
[1] 7

It's just a matter of definition. R and Breeze are using the unbiased estimate of population variance whereas numpy is using the MLE. It's not really a big deal either way, but statistician's have historically preferred the unbiased estimate.

**Comment by apoigne** [comment]
Thanks for clarification.
