### ISSUE TITLE
initialNonZero and VectorBuilder

### ISSUE THREAD

**Issue by superbobry** [scalanlp/breeze#619]
What is the semantics of the `initialNonZero` parameter in `VectorBuilder`? I would expect it to control the initial size of the `_data` and `_index` arrays, but apparently [it's not the case](https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/VectorBuilder.scala#L54).

**Comment by dlwh** [comment]
just an oversight, thanks for the report.
