### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Vannie92** [scalanlp/breeze#627]
Hello, i am new to scala and can't figure out installation, whenever i tried a following statement appeared:

Error Error while importing SBT project br/...br/pre[info] Resolving org.scala-sbt#tracking;0.13.7 
[info] Resolving org.scala-sbt#cache;0.13.7 ...
[info] Resolving org.scala-sbt#testing;0.13.7 ...
[info] Resolving org.scala-sbt#test-agent;0.13.7 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.7 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.7 ...
[info] Resolving org.scala-sbt#command;0.13.7 ...
[info] Resolving org.scala-sbt#logic;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.7 ...
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalanlp#breeze-natives_2.12;0.12: not found
[error] unresolved dependency: org.scalanlp#breeze-viz_2.12;0.12: not found
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: org.scalanlp#breeze-natives_2.12;0.12: not found
[error] unresolved dependency: org.scalanlp#breeze-viz_2.12;0.12: not found
[error] Total time: 17 s, completed Feb 26, 2017 9:57:06 AM
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0</pre><br/>See complete log in <a href="C:\Users\Vann\.IntelliJIdea2016.

Thanks in advance for any help

**Comment by nikdon** [comment]
There is no breeze-viz of version 0.12 for scala 2.12. Try to use instead last release 0.13 that is not mentioned in the readme:

```scala
...
"org.scalanlp" %% "breeze" % "0.13",
...
"org.scalanlp" %% "breeze-viz" % "0.13"
```

**Comment by Vannie92** [comment]
Thanks a lot it worked
