### ISSUE TITLE
add rank, svd for DM[Float]

### ISSUE THREAD

**Issue by qiaoruntao** [scalanlp/breeze#637]
Hello, 
I'm struggling with the usage of rank function.
The rank function is the one highlighted in the picture, it seems to take a Matrix type value and output an Int value.
![_20170427004433](https://cloud.githubusercontent.com/assets/5846433/25446047/c93357a6-2ae2-11e7-8d81-b44c15787d1a.png)
However I find it not possible to use it, when I try compiling following codes, it yields some errors with implicit value.
Following are my test codes:
```
    var test:Int=rank[DenseMatrix[Int],Int](DenseMatrix.eye[Int](3))
    test=rank(DenseMatrix.eye[Int](3))
    test=rank(DenseMatrix.eye[Float](3))
    test=rank(DenseVector.ones(1))
```

And these are the errors, none of four lines is passed:
![image](https://cloud.githubusercontent.com/assets/5846433/25446246/8d2549e4-2ae3-11e7-9644-83bd49868918.png)
I'm really confused why it cannot be compiled as it should be, simply take a DenseMatrix and return an Int or at least give the result since I provide enough type info.

My platform: win10 x64
Breeze version: 0.12 both breeze and breeze_native are added
Scala version: 2.11.8

thanks

**Comment by EvanOman** [comment]
`rank` is not defined for a `DenseMatrix[Int]` because Linear Algebra over the Integers is different than Linear Algebra over the Reals.

Try a `DenseMatrix[Double]` instead:
```
scala> import breeze.linalg._
import breeze.linalg._

scala> import breeze.numerics._
import breeze.numerics._

scala> val myMatrix = DenseMatrix.eye[Double](10)
myMatrix: breeze.linalg.DenseMatrix[Double] =
1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

scala> val myRank: Int = rank(myMatrix)
myRank: Int = 10
```

**Comment by qiaoruntao** [comment]
Sorry, I may not make myself clear. I tried getting rank from DenseMatrix[Float].
However the following code doesn't work:
`var test:Int=rank(DenseMatrix.eye[Float](3))`
The error is implicit value not found:
![image](https://cloud.githubusercontent.com/assets/5846433/25462711/7a4c3324-2b23-11e7-8f2b-b364a17a4bee.png)

I tried adding some type info into it, using code:
`var test:Int=rank[DenseMatrix[Float],Int](DenseMatrix.eye[Float](3))`
However there was no luck:
![image](https://cloud.githubusercontent.com/assets/5846433/25462748/a8f45d96-2b23-11e7-8e38-e5c9c2c3bb4a.png)

And yes Double type works, my code is:
`var test:Int=rank(DenseMatrix.eye[Double](3))`

So does this means rank function only supports Double? If this is true, support Float by default would be really great as they are different only by precision.

thanks

**Comment by EvanOman** [comment]
Yes it appears that `rank` is also not defined on `DenseMatrix[Float]` even though it should be. 

Looking at [`rank`](https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/functions/rank.scala) and [`svd`](https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/functions/svd.scala) there doesn't seem to be a good reason why `Float` doesn't work, I am guessing the fix would be minor.

**Comment by dlwh** [comment]
fixed
