### ISSUE TITLE
Easy interop between DenseMatrix[V] and Array[Array[V]]

### ISSUE THREAD

**Issue by Ichoran** [scalanlp/breeze#638]
In some cases, it is natural to store data as arrays of arrays.

If there is an easy way to go between this format and DenseMatrix, I haven't found it.  flatten/grouped are awkward and slow, and everything else is worse.  Thus I propose adding two new methods to `DenseMatrix` (companion and class, respectively):

```scala
def copiedFrom[V: blah blah](data: Array[Array[V]], transposeOnCopy: Boolean = false): DenseMatrix[V]

def toArrays: Array[Array[V]]
```

This will make interop trivial: `svd(DenseMatrix copiedFrom myData).S.toArrays`.

I am happy to write the implementations.  (I already have for myself, as I have a lot of data in Array[Array[Double]] format.)

**Comment by Raffaello** [comment]
is it not possible with this: https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/util/JavaArrayOps.scala ?
