### ISSUE TITLE
What's the status of nak and ML algorithms ?

### ISSUE THREAD

**Issue by unoexperto** [scalanlp/breeze#640]
Hey guys,

I'm considering switching to breeze. Therefore I have one question. What's the status of nak and ML algorithms ? Will the be migrated to breeze ?

I'm on Scala 2.11 with plan to switch to 2.12 soon.

**Comment by dlwh** [comment]
Nak is basically dead. Its maintainer got sucked into the Google blackhole.
I'm happy to entertain ports from Nak but I don't have the bandwidth or
inclination to do it myself. (If I was gonna build something it would look
much more like Dynet)

-- David

**Comment by unoexperto** [comment]
@dlwh That's sad. What would you recommend to use for ML ? I tried MALLET and StanfordNLP in the past but didn't like them much.

**Comment by dlwh** [comment]
It depends on what you need. MLLib in Spark has a lot of nice features if
your problems fit that mode. Epic's a bit on life support, but is pretty
solid if you need a CRF. Factorie is a pretty good graphical models
framework. Dynet-scala is not bad for neural nets

**Comment by debasish83** [comment]
For neural net, mxnet has good scala and spark integration...
