### ISSUE TITLE
VectorSpace[_, Double] in optimization

### ISSUE THREAD

**Issue by superbobry** [scalanlp/breeze#642]
Most of the optimization-related APIs require an instance of `VectorSpace[_, Double]` to work. Unfortunately, this doesn't allow to use these APIs over `Vector[Float]`, because IIUC there's no ready-made instances. I wonder if it is possible to relax the `Double` constraint somehow?

**Comment by debasish83** [comment]
Float is mostly useful for distributed shuffle...Idea is to shuffle float or any other optimized data structure but it can converted to Double before optimization can be run...due to precision issues, it's risky to run optimization using Float or lower precision.

**Comment by superbobry** [comment]
Thanks @debasish83, this makes sense. One possible solution for this is to provide the instances for `VectorSpace[Vector[Float], Double]`, because right now the users are forced to reverse-engineer how to do that or just give up and do nothing :)

**Comment by dlwh** [comment]
fixed in d5d04a9
