### ISSUE TITLE
how to do breeze pow  method of DenseVector for java ?

### ISSUE THREAD

**Issue by kervin521** [scalanlp/breeze#649]
in Spark MLlib ,Scala Code:

import breeze.linalg._
import breeze.numerics.pow
def computeDistance(v1: DenseVector[Double], v2: DenseVector[Double])
= pow(v1 - v2, 2).sum

Spark Machine Learning refering :  the pow function is a global function of Breeze

but I can't found pow method of breeze jar for java

how to solve?

**Comment by dlwh** [comment]
Breeze is not designed to be called from Java, sorry.
