### ISSUE TITLE
HashVector/SparseVector binary operations are inefficient

### ISSUE THREAD

**Issue by superbobry** [scalanlp/breeze#653]
It seems all of the binary operations on `HashVector` work in O(size) instead of O(activeSize). Here's an example:

```scala
val x = HashVector.zeros[Double](Int.MaxValue - 1)
val y = SparseVector.zeros[Double](Int.MaxValue - 1)
x :+= y
```

The stracktrace points to [`hv_hv_UpdateOp`](https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/operators/HashVectorOps.scala#L221) which indeed does a O(size) update, but surprisingly `+` is not among the ones supported by this implicit.

**Comment by dlwh** [comment]
(more apologies for tardiness) you can see right below that Add is handled via the one right below it, because it's 0-idempotent. I guess I didn't think it through at the time and you only need LHS idempotence. I'll fix now

**Comment by dlwh** [comment]
ok, took a bit longer than I would have liked, but I think I have the basic big-o right for these now. Could definitely improve things further by using primitive loops, but eh

https://github.com/scalanlp/breeze/compare/f6d83084e58413c7b07c9a72d8d8745df3159da4~3...f6d83084e58413c7b07c9a72d8d8745df3159da4
