### ISSUE TITLE
reshape not working properly

### ISSUE THREAD

**Issue by timotta** [scalanlp/breeze#655]
This test is not passing:

```scala
    val dense = DenseMatrix(
        DenseVector(1D, 2D, 1D, 2D, 1D, 2D),
        DenseVector(3D, 4D, 3D, 4D, 3D, 4D))

    val reshaped = dense.reshape(6, 2)
    val expected = DenseMatrix(
        DenseVector(1D, 2D),
        DenseVector(1D, 2D),
        DenseVector(1D, 2D),
        DenseVector(3D, 4D),
        DenseVector(3D, 4D),
        DenseVector(3D, 4D))

    Assert.assertEquals(expected, reshaped)
```

Result in Breeze is:

```
1.0  2.0  
3.0  4.0  
2.0  1.0  
4.0  3.0  
1.0  2.0  
3.0  4.0
```

NumPy works fine:

```python
>>> import numpy as np
>>> dense = np.array([[1,2,1,2,1,2], [3,4,3,4,3,4]])
>>> dense.reshape(6,2)
array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])
```

I'm using: org.scalanlp:breeze_2.11:0.13.2

**Comment by EvanOman** [comment]
Breeze uses column major ordering while NumPy uses row major ordering (read more about these orderings [here](https://en.wikipedia.org/wiki/Row-_and_column-major_order)). The major ordering determines how values will be ordered in operations like `reshape`.

**Comment by timotta** [comment]
So maybe the bug is in the cheat sheet, because the behavior of numpy reshape is different from breeze reshape.
