### ISSUE TITLE
DenseMatrix of generic type

### ISSUE THREAD

**Issue by mike-grayhat** [scalanlp/breeze#656]
Hi! Thank you for a great library!

Is there a way to define a DenseMatrix of generic type? I'm trying to do run a code similar to this one:

```scala

class MaskedMatrix[T](data: DenseMatrix[T],
                                     col_indices: Map[String, Int],
                                     default:T) {

  val columns = col_indices.keys
  var mask = DenseMatrix.ones[Boolean](data.rows, data.cols)

  def masked_data: DenseMatrix[T] = {
    data.mapPairs({
      case ((r, c), v) if mask(r, c) => v
      case _ => default
    })
  }

```

but i get compilation error "could not find implicit value for parameter bf".

**Comment by dlwh** [comment]
Sorry for not responding sooner. you need an implicit ClassTag[T] so that it knows how to make the result array. `class MaskedMatrix[T: ClassTag]`
