### ISSUE TITLE
DenseVector to DenseMatrix?

### ISSUE THREAD

**Issue by saarraz** [scalanlp/breeze#66]
Is there a method to convert an m-length DenseVector into an m-by-1 or an 1-by-m matrix?

**Comment by kapilkd13** [comment]
@saarraz I am using this function, but it turns out to be highly expensive operation for me. takes 300-400 ms for a dense vector of size 5,00,000. Is this normal and can we reduce it somehow

**Comment by ZpWaitingForSunshine** [comment]
.asDenseMatrix
I think this function may help you
