### ISSUE TITLE
SparseArray does not implement equals

### ISSUE THREAD

**Issue by nightscape** [scalanlp/breeze#661]
AFAIS `SparseArray` does not implement a proper equals method.
There are many tests though that compare `SparseArray`s or `SparseVector`s (which contain `SparseArray`s) and fail accordingly.
Is there a reason behind this?
If not, shall I create a PR?

**Comment by dlwh** [comment]
it used to... there was some todo about this not that long ago. maybe i
messed up a PR merge

**Comment by dlwh** [comment]
this is fixed
