### ISSUE TITLE
FunctionValuesConverged with relative = true

### ISSUE THREAD

**Issue by siqil** [scalanlp/breeze#664]
For checking the convergence based on function values, we have the condition:

`info.length >= 2 && (state.adjustedValue - info.max).abs <= tolerance * (if (relative) state.initialAdjVal else 1.0)`

My understanding is that it checks whether the absolute difference between the recent maximum and current adjusted value is less than or equal to the tolerance scaled by the initial adjusted value (for relative = true). If that's correct, then imagine a function having negative values from the initial point till the minimum. Then this condition can never be satisfied, right? Shouldn't we use abs also on the RHS of the inequality?

**Comment by dlwh** [comment]
yep, good catch!
