### ISSUE TITLE
Illformed creation of breeze.collection.mutable.RingBuffer via Companion Object

### ISSUE THREAD

**Issue by schlichtanders** [scalanlp/breeze#666]
RingBuffer creation via Companion Object is buggy.

If using ``varargs`` creation or ``fill``, both don't construct a RingBuffer of the respective Size, but an apparently infinite RingBuffer, which at least to me seems to be a semantically buggy concept.

this code
```scala
import breeze.collection.mutable.RingBuffer

val rb = RingBuffer(1,2,3)
rb += 4

val rb2 = RingBuffer.fill(3)(0)
rb2 += 1
```
outputs the following in scala worksheet
```
import breeze.collection.mutable.RingBuffer

rb: breeze.collection.mutable.RingBuffer[Int] = RingBuffer(1, 2, 3)
res0: rb.type = RingBuffer(1, 2, 3, 4)

rb2: breeze.collection.mutable.RingBuffer[Int] = RingBuffer(0, 0, 0)
res1: rb2.type = RingBuffer(0, 0, 0, 1)
```

but should output
```
import breeze.collection.mutable.RingBuffer

rb: breeze.collection.mutable.RingBuffer[Int] = RingBuffer(1, 2, 3)
res0: rb.type = RingBuffer(2, 3, 4)

rb2: breeze.collection.mutable.RingBuffer[Int] = RingBuffer(0, 0, 0)
res1: rb2.type = RingBuffer(0, 0, 1)
```

**Comment by dlwh** [comment]
so sorry for the slow reply. new baby and work and such.

So, the RingBuffer implementation was mostly just not clear about the semantics of those constructors: it always used Int.MaxValue for the capacity when using companion constructors.

I have changed the RB implementation substantially:

* to make it an actually normal, efficient-ish implementation of a RingBuffer
* to remove the factory methods like fill and simple `apply`.

Now, you can either do `new RingBuffer[T](capacity)` or `RingBuffer[T](capacity)(elems)`
