### ISSUE TITLE
Cannot call normalize() on a DenseVector[Float]?

### ISSUE THREAD

**Issue by cjdudley1** [scalanlp/breeze#667]
Hi, 

We've been using DenseVector[Float] in a project, but have encountered issues calling the normalize() function on them, and get the following error:

`could not find implicit value for parameter impl: breeze.linalg.normalize.Impl[breeze.linalg.DenseVector[Float],VR]`

I've looked into the source code, and noticed that normalizeImpl is defined for Doubles (line 52 of  normalize.scala) but not for Floats; could this be the source of the issue? If so, is this deliberate or something that can be added?

Thanks!

**Comment by dlwh** [comment]
So sorry for the slow reply. New baby and hectic work stuff.

I will add it now. Breeze mostly has support for Doubles, with only so-so coverage for Floats. I should do better, but I haven't yet.
