### ISSUE TITLE
Error:(23, 23) could not find implicit value for parameter impl: breeze.stats.hist.Impl2[IndexedSeq[String],Int,VR]   f.subplot(0) += hist(ys,3)

### ISSUE THREAD

**Issue by vkhanduja** [scalanlp/breeze#668]
I have a sample program which seems to compile but giving a runtime error.

Error:(23, 23) could not find implicit value for parameter impl: breeze.stats.hist.Impl2[IndexedSeq[String],Int,VR]
  f.subplot(0) += hist(ys,3)

Sample code:

................................

import breeze.plot.Figure
import breeze.stats.hist
import breeze.linalg._
import org.saddle.io._

object BostonData extends App {

  val file = CsvFile("train.csv")

  val df = CsvParser.parse(file).withColIndex(0)

  val f = Figure()

  f.width = 800

  f.height = 800

  val ys = for (y <- df.colAt(13).toSeq) yield y._2

  f.subplot(0)

  f.subplot(0) += hist(ys,3)

}
...............................

**Comment by dlwh** [comment]
you're calling the wrong `hist`. You should call breeze.plot.hist (unfortunate name collision, I know.)
