### ISSUE TITLE
DenseVector.rangeD creates too shorter vector.

### ISSUE THREAD

**Issue by mysticatea** [scalanlp/breeze#669]
`DenseVector.rangeD(start, end, step)` method creates a too short vector.
I guess [Vector.scala#L957](https://github.com/scalanlp/breeze/blob/8a22719d9ba74eedbe65548ff6e0987e47669640/math/src/main/scala/breeze/linalg/Vector.scala#L957) seems wrong.
It needs the logic similar to [scala/collection/immutable/Range.scala#L423-L426](https://github.com/scala/scala/blob/c5dc46457fee0289f23ac126fcfa4c75b10bc45a/src/library/scala/collection/immutable/Range.scala#L423-L426)

**What did you do?**

```scala
scala> DenseVector.rangeD(0, 10, 3)
res1: breeze.linalg.DenseVector[Double] = DenseVector(0.0, 3.0, 6.0)
```

**What did you expect to happen?**

I expected to get `DenseVector(0.0, 3.0, 6.0, 9.0)` because `9.0` is less than `10.0`.

**What actually happened?**

I got `DenseVector(0.0, 3.0, 6.0)` as lacking `9.0`.

**Comment by dlwh** [comment]
So sorry for the slow reply. New baby and hectic work stuff. fixing now

**Comment by mysticatea** [comment]
Thank you!
