### ISSUE TITLE
Image writing

### ISSUE THREAD

**Issue by nlw0** [scalanlp/breeze#670]
I wrote a nice little function to save a png image from a breeze matrix, and I would like to contribute it to the project. Is there an interest? Should I put it in breeze.io? Any recommendations for the interface?

**Comment by nlw0** [comment]
Not sure if I should make a PR already, but this is how it looks like https://github.com/nlw0/breeze/blob/master/math/src/main/scala/breeze/io/ImageIO.scala

I'm having some trouble to build the library in my ancient computer, so it's hard to test it properly right now.

**Comment by dlwh** [comment]
Hi @nlw0, sorry about the slow reply.

That would be great!
