### ISSUE TITLE
Bugfix release

### ISSUE THREAD

**Issue by superbobry** [scalanlp/breeze#677]
Hi @dlwh, `master` has quite a few fixes which would make Breeze users happier. Do you think you could do a bugfix release in the 0.13.X branch?

**Comment by dlwh** [comment]
I was hoping to knock out a bit more of https://github.com/scalanlp/breeze/milestone/5 and then just declare 1.0

WDYT?

-- David

**Comment by superbobry** [comment]
Well, as a user requesting a bugfix release I'm a bit biased here :) but I'd say it depends on how long do you think it'd take to complete everything in the milestone. Do you plan to finish it in 1-2 months?

**Comment by dlwh** [comment]
fair enough. I'm not in a place where I can release anything until at least
this weekend, but I'll try to do it then

**Comment by dlwh** [comment]
i'm gonna do this today hopefully
