### ISSUE TITLE
Friendlier LU Decomposition API

### ISSUE THREAD

**Issue by ZacBlanco** [scalanlp/breeze#680]
I needed to perform LU decomposition on a matrix. While breeze does provide an interface for it, the returned results aren't as easily usable as, say, the numpy/scipy LU-decomposition interface.

[https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.lu.html](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.lu.html)

It would be nice if Breeze's interface was similar to SciPy's where you can individually get the upper and lower triangular matrices, instead of them packed together like LAPACK returns.

I've written some methods which decompose the output and permutation matrix to get the three matrices (P, L, and U) that are returned similar to SciPy.

See [https://github.com/ZacBlanco/spark/blob/master/mllib/src/main/scala/org/apache/spark/mllib/linalg/distributed/fastSVD.scala#L361-L400](https://github.com/ZacBlanco/spark/blob/master/mllib/src/main/scala/org/apache/spark/mllib/linalg/distributed/fastSVD.scala#L361-L400)

I'm sure I could polish the code some more. Would this be a welcomed change?

**Comment by dlwh** [comment]
yes that would be great!

**Comment by ZacBlanco** [comment]
PR #681 opened for these changes
