### ISSUE TITLE
breeze depends on GPL licenced jtransforms despite licenced under Apache 2.0

### ISSUE THREAD

**Issue by lin-zhao** [scalanlp/breeze#686]
`math` depends on following that's listed as GPL2, LGPL2, which are imcompatible with Apache 2.0.

https://mvnrepository.com/artifact/com.github.rwl/jtransforms/2.4.0

**Comment by dlwh** [comment]
ah crap, i swore we depended on the BSD version.

**Comment by dlwh** [comment]
fixed in 345b3094
