### ISSUE TITLE
Submatrix as View

### ISSUE THREAD

**Issue by dclong** [scalanlp/breeze#687]
Does breeze support a submatrix as view? That is the submatrix does not make a copy of data but instead using data from the original matrix.

**Comment by dlwh** [comment]
yes, the default slicing mechanism produces views, with some caveats. Namely, you can't use non-1 strides on the minor axis (which is rows by default).

**Comment by dclong** [comment]
Sorry that I'm relative new to breeze. Can you elaborate a little bit on "non-1 strides"? An illustration is great.

**Comment by dlwh** [comment]
yeah, the docs aren't great yet. sorry.

Short answer is:

`dm(3 until 11, 0 until 10 by 3)` is ok for matrices with `!isTranspose` (which is the default). the column axis has a stride of 3, which means that only every third column is taken.

You can't have a stride of 3 (or anything other than 1) for the rows of the matrix, unless `isTranspose`.

This is a technical limitation of the underlying data representation for DenseMatrices, which we inherited from BLAS/Fortran. In retrospect, I could have worked around it, but here we are.
