### ISSUE TITLE
Type mismatch when compiling 

### ISSUE THREAD

**Issue by dclong** [scalanlp/breeze#688]
I use matrix slicing m(::, i) and then got a type mismatch error when compiling. 

found: collection.immutable.::.type
rquired: Int

Do I have to import an implicit conversion for it to work?

**Comment by dlwh** [comment]
Slicing only works on DenseMatrices

**Comment by dclong** [comment]
I compiled the following code, but still an error of "type mismatch". 
```
import breeze.linalg.DenseMatrix
import breeze.linalg.DenseVector

object RunBreeze {

  def main(args: Array[String]): Unit = {
    val m = DenseMatrix.zeros[Double](5, 3)
    m(::, 1) = DenseVector(1.0, 2.0, 3.0, 4.0, 5.0)
  }
}
```
Below is my build.sbt
```
name := "test"

version := "0.1"

scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  "org.scalanlp" %% "breeze" % "0.13.2"
)
```

**Comment by brainyvoyage** [comment]
@dclong Use `:=` operator in line `m(::, 1) = DenseVector(1.0, 2.0, 3.0, 4.0, 5.0)`.
