### ISSUE TITLE
Application does not take parameters

### ISSUE THREAD

**Issue by Mark110** [scalanlp/breeze#689]
I use sbt.build down jar.but when I use plot ,it appears application does not take parameters.how I resolved the problem.

**Comment by dlwh** [comment]
i need a code sample. that's not nearly enough information

**Comment by Mark110** [comment]
Do you have email?when I practice the machine learning,I plot the figure which I plot k in the kmeans and WSSSE ,the problem happened.

**Comment by dlwh** [comment]
github handle @ cs.berkeley.edu

please send something small. the smallest thing that can reproduce this
error

**Comment by Mark110** [comment]
I can't go into github handle @ cs.berkeley.edu.I only go into cs.berkeley.edu.The parameter of the plot function is transformed the DenseVector

**Comment by dlwh** [comment]
can you please give me a code sample (uploaded to gist.github.com) that,
when i run the compiler on it, produces the same problem.

**Comment by Mark110** [comment]
Sorry.I cannot go into the web.I am in China.

**Comment by dlwh** [comment]
can you paste something here?

**Comment by Mark110** [comment]
I use your document.Also disappear same problem

**Comment by Mark110** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.immutable.Range.validateRangeBoundaries(Lscala/Function1;)Z
