### ISSUE TITLE
Is breeze 0.13 incompatible with Spark 2.0.x?

### ISSUE THREAD

**Issue by pcrwebdesign** [scalanlp/breeze#690]
I have created a minimalistic scala project (scala 2.11) that only includes Spark 2.0.0 and the version 0.13 of the breeze library. That is, the only libraryDependencies are:
```
"org.apache.spark" % "spark-core_2.11" % "2.0.0" % "provided"
"org.scalanlp" % "breeze_2.11" % "0.13"
```

There is a single file with a main method that tries to calculate the mean of a DenseVector. This is the only code:
```
package com.clipinteractive.breezespark

import breeze.linalg._
import breeze.stats._

object Breezespark {
  def main(args: Array[String]): Unit = { 
    val dv = DenseVector(1.0, 2.0, 3.0)
    printf("MEAN = " + mean(dv))
  }
}
```
Running the uber jar with `scala uber-breezespark.jar` produces the right result without issues. Running it with spark-submit as in:
`spark-submit --class com.clipinteractive.breezespark.Breezespark uber-breezespark.jar` 
fails miserably with a NoSuchMethodError. The exact error is:

Exception in thread "main" java.lang.NoSuchMethodError: breeze.stats.package$.mean()Lbreeze/stats/DescriptiveStats$mean$;

Version 2.0.2 of Spark has exactly the same issue. However version 0.11 of breeze runs just fine.

**Comment by ZacBlanco** [comment]
You can find the version of breeze that spark uses by looking at the pom.xml file in the apache spark directory on the 2.0.x branch

[https://github.com/apache/spark/blob/branch-2.0/pom.xml#L668-L684](https://github.com/apache/spark/blob/branch-2.0/pom.xml#L668-L684)

Looks like to me that the breeze version used for spark is 0.11.2. This would explain why you found that 0.11 works and other versions don't.

**Comment by dlwh** [comment]
I actually answered this on the mailing list and forgot to close it: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/scala-breeze/raEiK671Gp8/U6jVNQhuBAAJ
