### ISSUE TITLE
Set seed for DenseVector initialization?

### ISSUE THREAD

**Issue by andb0t** [scalanlp/breeze#696]
Hello,
I've been searching the web and the code for a way to initialize the random seed for the initialization of e.g. DenseVectors, such that the result of e.g.
```scala
DenseVector.rand[Double](2,2)
```
becomes reproducible. Is there a way to do it? I'd be glad to extend e.g. the help and cheatsheets by this feature, if it exists.
Cheers!

**Comment by dlwh** [comment]
There's a final argument to rand that takes a
breeze.stats.distributions.Rand[T]. It defaults to Rand.uniform. You can
replace it with a rand that you seed
