### ISSUE TITLE
Breeze-vis headless - without GUI

### ISSUE THREAD

**Issue by andb0t** [scalanlp/breeze#699]
Hi all,

I'm developing on WSL (the windows subsystem for Linux), which is a full Ubuntu system, but without X server access (yet). So in a way it's like a jenkins container without X server. The problem I'm having when trying to create and save plots (just the simple example from the [Quickstart guide](https://github.com/scalanlp/breeze/wiki/Quickstart#breeze-viz) is this:
```scala
[error] (run-main-136) java.awt.HeadlessException:
[error] No X11 DISPLAY variable was set, but this program performed an operation which requires it.
```
Is the X server necesary for the plot creation or is there a work-around? Or anything you an advise me to google to fix it?

Cheers!

**Comment by darrenjw** [comment]
Set
```scala
f.visible=false
```
immediately after 
```scala
val f = Figure()
```

**Comment by andb0t** [comment]
This breaks already:
```scala
    println("val f = Figure()")
    val f = Figure()
    println("f.visible= false")
    f.visible= false
    println("val p = f.subplot(0)")
    val p = f.subplot(0)
```
results in
```scala
val f = Figure()
f.visible= false
[error] (run-main-13a) java.awt.HeadlessException:
[error] No X11 DISPLAY variable was set, but this program performed an operation which requires it.
```

**Comment by darrenjw** [comment]
Sorry - yes - you're right. I thought I'd tested it, but I'd actually tested it in a cmd window rather than a bash window... There's probably a horrible hack for this where you run a dummy X server, but I don't have any other solution.

**Comment by EvanOman** [comment]
You can open an X Server Window with WSL no problem. Just install [Xming X Server](https://sourceforge.net/projects/xming/files/), run `XLaunch`, and add the following to your `.bashrc` file

```
 # Setting for XServer windows 
export DISPLAY=:0
```

Doing so I am able to make the plots like so: 

![image](https://user-images.githubusercontent.com/1807879/36926490-bdc6fa86-1e3d-11e8-9841-b390443d7105.png)

**Comment by andb0t** [comment]
Brilliant, that works! Thanks a lot, guys!
