### ISSUE TITLE
[help needed] transparently add a vector (broadcast) to a matrix 

### ISSUE THREAD

**Issue by mdespriee** [scalanlp/breeze#702]
(Not sure if github issues are the proper place to ask for help, re-route if needed)

I have a series of matrices that I add in a Seq(...).reduce(_ + _) fashion

Those matrices may be sometimes vectors, and in that case, I need to do a broadcast. Currently I'm doing a first pass on the list to get the size of each matrix and apply the broadcast if necessary.

I'd like to do it in a more transparent way (a bit like in numpy). Can it be done through the use of UFuncs or through the magics of implicits ?

Thanks for your insights

**Comment by dlwh** [comment]
I don't think so, sorry.

(Totally fine to ask questions here.)
