### ISSUE TITLE
breeze package not compatible with Spark 2.2.1

### ISSUE THREAD

**Issue by mimrezash** [scalanlp/breeze#710]
I have a spark application that uses ARIMA model for time series. When I am running the application using spark 2.2.1 I get this error :
`Caused by: java.lang.NoSuchMethodError: breeze.linalg.DenseVector$.canSetD()Lbreeze/generic/UFunc$InPlaceImpl2;
	at com.cloudera.sparkts.models.ARIMAModel.gradientlogLikelihoodCSSARMA(ARIMA.scala:506)
	at com.cloudera.sparkts.models.ARIMA$$anon$3.value(ARIMA.scala:189)`

But when I use an older version of spark 2.0.2 the application works. Apparently, the new spark is trying to call a function in the breeze package that does not exist anymore. I am not sure this issue needs to be addressed by breeze team or spark-timeseries team.

**Comment by dlwh** [comment]
you have to use the right version of breeze with spark. Spark uses breeze and you shouldn't need to include breeze yourself when you use it from spark
