### ISSUE TITLE
Help for online logistic regression implementation with AdaptiveGradientDescent

### ISSUE THREAD

**Issue by alexisdurieux** [scalanlp/breeze#712]
I am trying to perform online sparse (around 10e6 features) logistic regression using `AdaptiveGradientDescent` but I'm having difficulties to understand the code base. What I want to perform is a one by one example. Given my understanding of the `FirstOrderMinimizer` what I have to do is to give it `DiffFunction`.

```scala
case class OnlineLogisticDiffFunction(oneExample: LogisticExample) extends DiffFunction[SparseVector[Double]] {
    override def calculate(x: SparseVector[Double]): (Double, SparseVector[Double]) = {
      val vb: VectorBuilder[Double] = new VectorBuilder(length = x.size)
      oneExample.features.activeKeysIterator.foreach { key =>
        vb.add(key, x(key))
      }
      val z: Double = vb.toSparseVector.dot(oneExample.features)
      val prediction = logisticScore(z)
      val error = prediction - oneExample.label
      val gradient = oneExample.features *:* error

      (if (oneExample.label > 0) -Math.log(prediction) else Math.log(1 - prediction), gradient)
    }
  }
```

`LogisticExample` is just a case class wrapping an example's features and label into respectively a `SparseVector` and a `Double`

Then my logistic regression looks like:
```scala
val sgd = new AdaptiveGradientDescent.L2Regularization[SparseVector[Double]](stepSize = 1.0, maxIter = 1)
val initWeights = new VectorBuilder[Double]().toSparseVector
val optimizedWeights: SparseVector[Double] = examples.foldLeft(initWeights) { case (weights, example) =>
      val onlineLogisticDiffFunction = OnlineLogisticDiffFunction(example)
      sgd.minimize(onlineLogisticDiffFunction, weights)
    }
```

`examples` is an `Iterator[LogisticExample]` that allows me to udpate the `DiffFunction` with every example.

The problem of my implementation is the **execution time** (around 300ms) per example. After investigation, the `SparseArray.indexOf` method is responsible though the `used` size in the `DiffFunction.calculate` for the `gradient` is ok.

It looks to me that I'm missing something in the use of the *FirstOrderMinimizer* but I can't put my finger on it.

- Is it the correct way to iterate through the examples to perform gradient descent ?
- If so, should the execution time be that long or is it an issue with the way I'm using SparseVector ?

Thanks for your help !

EDIT 1: After further investigation, it seems the slow execution comes from the use of `sqrt` on a `SparseVector` which then returns a SparseVector where `used = size`

**Comment by dlwh** [comment]
ugh, yeah, that's a limitation to the typeclass approach we're using, sadly
