### ISSUE TITLE
breeze DenseVectors (and possibly others) have bounded types in foldLeft.

### ISSUE THREAD

**Issue by espears4sq** [scalanlp/breeze#720]
I was looking at the [definition of `foldLeft` for `Vector`](https://github.com/scalanlp/breeze/blob/58b3f511f20521cdae0c09429ad278e8bec5a7f6/math/src/main/scala/breeze/linalg/Vector.scala#L114)

```
def foldLeft[B >: V](z: B)(op: (B, V) => B): B = valuesIterator.foldLeft(z)(op)
```

Comparing with the [signature for basic `foldLeft`, such as for `List`](https://www.scala-lang.org/old/node/12050.html), the basic implementation is fully generic over the accumulator output type.

In fact, this seems to be one of the specific reasons someone might be directed to use `foldLeft` over `fold`, when you want the accumulator output type to be arbitrary and potentially unrelated to the element type of the underlying container.

For e.g. `DenseVector` this can be a huge pain. Consider trying to count the number of elements where two different `DenseVector`s are equal.

```
scala> val x = DenseVector(1.0, 2.0, 3.0)
x: breeze.linalg.DenseVector[Double] = DenseVector(1.0, 2.0, 3.0)

scala> val y = DenseVector(3.0, 2.0, 1.0)
y: breeze.linalg.DenseVector[Double] = DenseVector(3.0, 2.0, 1.0)

scala> val w = (x :== y)
w: breeze.linalg.BitVector = BitVector(1)


scala> w.toDenseVector // note: fold over BitVector was even harder to deal with
res114: breeze.linalg.DenseVector[Boolean] = DenseVector(false, true, false)

scala> w.toDenseVector.map(i => if(i) 1 else 0).sum
res115: Int = 1

scala> w.toDenseVector.foldLeft(0)( (acc, i) => if(i) acc + 1 else acc)
<console>:15: error: type mismatch;
 found   : Int(1)
 required: String
       w.toDenseVector.foldLeft(0)( (acc, i) => if(i) acc + 1 else acc)
```

But folding over a `List[Boolean]` to get back a count of the `true` values, for example, is a perfectly standard operation.

Why does `Vector` have this type bound limitation in `foldLeft` (and presumably other operations, and perhaps for matrix types and other types)?

**Comment by dlwh** [comment]
it's just a dumb limitation. probably i or whoever wrote it wasn't thinking and I didn't catch it.

**Comment by espears4sq** [comment]
@dlwh Thank you for your reply. I would be happy to make an attempt to fix this in a PR. I might need some help pointing me in the right direction. I was not easily able to figure out where in the hierarchy the change would need to be made, and where to test so that all impacted places that inherit this type signature can be checked. I suppose it could also be possible that some user code could break, if it relies on the type bound in some esoteric way. That seems incredibly unlikely though and could be communicated in release notes for whatever future version.

Let me know any tips on helping out if you would like.

**Comment by dlwh** [comment]
I think you can probably just fix the signatures in Vector and just fix the fallout from the compiler. I agree the risk to client code is minimal

**Comment by espears4sq** [comment]
@dlwh Please see the PR above. Let me know if any additional changes are required.
