### ISSUE TITLE
Linear Algebra support for Complex Matrices isn't great

### ISSUE THREAD

**Issue by VarianL** [scalanlp/breeze#724]
It would be good to more fully support complex numbers:

- [ ] inv
- [ ] eig
- [ ] svd
- [ ] ...

Original:

In my project I have to compute complex matrix.But inv does not seem to support complex matrix .
I have no idea about how to compute complex matrix inverse.I really need your help

**Comment by dlwh** [comment]
sorry for being slow. the complex support isn't good and probably won't be.

**Comment by dlwh** [comment]
dupe of #502 actually...
