### ISSUE TITLE
Vector * Vector does not work

### ISSUE THREAD

**Issue by schlichtanders** [scalanlp/breeze#728]
with scala 2.11.12, breeze 0.12 the following astonishingly basic operation does not work
```scala
val b = breeze.linalg.DenseVector(1.0,2.0,3.0)
b * b
```
but throws the following error
```
diverging implicit expansion for type breeze.linalg.operators.OpMulMatrix.Impl2[breeze.linalg.DenseVector[Double],breeze.linalg.DenseVector[Double],That]
starting with method collapseUred in object UFunc
       b * b
```

**Comment by akopich** [comment]
If you need a dot-product, you should rather use 
```scala
a.t * a
```
or
```scala
dot(a, a)
```

Your version doesn't work because `DenseVector` stands for a column-vector and a product of two column vectors is not defined.

**Comment by schlichtanders** [comment]
thank you very much for the fast response!!

I was experimenting a bit in the meanwhile and found that ```b :* b`` does give a element-wise product in breeze 0.12
