### ISSUE TITLE
Column-wise sum results in ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by changhiskhan** [scalanlp/breeze#735]
I'm on Spark 2.3.0 which should be Breeze 0.13.2?
Let me know if you need other info please. Integer overflow issue?

![image](https://user-images.githubusercontent.com/759245/49180386-55878480-f309-11e8-83d3-83ef69849fca.png)

**Comment by dlwh** [comment]
breeze uses java arrays to back its dense matrices, so there's a hard limit of roughly 2^31 elements per matrix.
