### ISSUE TITLE
Compiler finding wrong .apply

### ISSUE THREAD

**Issue by kesinger** [scalanlp/breeze#741]
Consider: 

```
  def f(n: Integer) : Double = {
    val prec : DenseVector[Double] = DenseVector.ones[Double](n+1)
    prec(n-1)
  }

```
This compiles fine and runs as expected.  Changing it sightly tho:

```
  def f2(n: Integer) : Double = {
    val prec : DenseVector[Double] = DenseVector.ones[Double](n+1)
    prec(n)
  }

```
I get this error: 

```
   error: could not find implicit value for parameter canSlice: breeze.linalg.support.CanSlice[breeze.linalg.DenseVector[Double],Integer,Result]
         f2(n)

```

Using scala 2.12.8, breeze 0.13.2

**Comment by dlwh** [comment]
sorry for being slow. You should use Int not Integer. Integer is the boxed JVM type, while Int is (usually) primitive. In the former example, n -1 coerces n to an Int. Breeze/Scala aren't smart enough to coerce the Integer to Int for apply. Really I think Scalac should handle this particular example.
