### ISSUE TITLE
SparseVector index.length and data.length not consistent with size

### ISSUE THREAD

**Issue by fracting** [scalanlp/breeze#742]
Dear folks,

The following code outputs something weird to me:

```
import breeze.linalg.SparseVector

object Main extends App {
  val bsv1 = new SparseVector[Double](Array(1, 2, 3), Array(1.0, 1.0, 1.0), 4)
  printf("bsv1: ")
  println(bsv1)
  printf("bsv1.size: %d\n", bsv1.size)
  printf("bsv1.activeSize: %d\n", bsv1.activeSize)
  printf("bsv1.index.length: %d\n", bsv1.index.length)
  printf("bsv1.data.length: %d\n", bsv1.data.length)
  println()

  val bsv2 = bsv1 * 1.0
  printf("bsv1 equals bsv2:")
  println(bsv2.equals(bsv1))
  printf("bsv2: ")
  println(bsv2)
  printf("bsv2.size: %d\n", bsv2.size)
  printf("bsv2.activeSize: %d\n", bsv2.activeSize)
  printf("bsv2.index.length: %d\n", bsv2.index.length)
  printf("bsv2.data.length: %d\n", bsv2.data.length)
}
```

Output:
```
bsv1: SparseVector(4)((1,1.0), (2,1.0), (3,1.0))
bsv1.size: 4
bsv1.activeSize: 3
bsv1.index.length: 3
bsv1.data.length: 3

bsv1 equals bsv2:true
bsv2: SparseVector(4)((1,1.0), (2,1.0), (3,1.0))
bsv2.size: 4
bsv2.activeSize: 3
bsv2.index.length: 4
bsv2.data.length: 4
```

I'm using:
```
$ uname -a
Darwin C02WJ1HKG8WL 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

scalaVersion := "2.11.12"

"org.scalanlp" %% "breeze" % "0.13.2"
```

I noticed that breeze inserts an extra zero in both `index` and `data`, which is fine in most case, only when I try to convert breeze SparseVector to spark SparseVector using the following way it causes trouble.

https://stackoverflow.com/a/54281609/4647224

My workaround is adding a slice like this:
```
new SparseVector(sv.length, sv.index.slice(0, sv.activeSize), sv.data.slice(0, sv.activeSize))
```

Does it consider a bug?

Thank you!

**Comment by dlwh** [comment]
it's not a bug.

`size` is the "logical" length of the vector, in analogy to DenseVector's length. (Vectors must have the same size for most binary operations)

activeSize is the number of non-zero values (well, technically, the number of values we're using storage for).

To maintain reasonably fast append/insertion, we use a doubling strategy for the actual length of the index and values arrays. I dunno if that's actually a good idea; it was done a long time ago and i don't think really ever tested for performance.
