### ISSUE TITLE
Is breeze going to be ported to dotty?

### ISSUE THREAD

**Issue by vicaba** [scalanlp/breeze#748]
Simple question. Is breeze going to be ported to dotty/Scala 3? How likely it is to be ported?

**Comment by dlwh** [comment]
I mean, it depends on a lot of factors (ease of porting, how hard it is to
maintain scala 2.x and 3.x versions, how well the dotty-linker replacement
for specialized works) and I would appreciate help with it no matter what.
I will definitely support 2.13 (going to make it happen real soon now).

I would like to support dotty, but I recognize that I have fairly limited
time these days.

Also, I'm increasingly convinced that breeze is the wrong way to do linear
algebra/numerics, and you want something more like tensorflow/XLA, which
somewhat decreases my motivation to do too much. dotty-linker might support
this, but i haven't looked into it enough

-- David

**Comment by vicaba** [comment]
Good to hear about that. This gives me hints about what should I do with my project. Let's see what dotty can bring.

**Comment by unoexperto** [comment]
@vicaba Dotty can use 2.12 artifacts out of the box.

**Comment by Sciss** [comment]
Any news on this? Will you release Scala 3 artifacts?
