### ISSUE TITLE
Possible issue with rangeD vector constructor

### ISSUE THREAD

**Issue by vagmcs** [scalanlp/breeze#751]
Hello,

It seems there is an issue with rangeD function in VectorConstructor trait, unless the API changed for some reason (also related to issue #669).

Example:
```scala
DenseVector.rangeD(0.9, 1.1, 0.1)
```
**According to `breeze-0.13.2` I expected that this call should return the following DenseVector**
```scala
DenseVector(0.9, 1.0)
```

**However, I actually get**
```scala
DenseVector(0.9, 1.0, 1.1)
```

That happens due to the `math.ceil` call in [line 986](https://github.com/scalanlp/breeze/blob/aeb3360ce77d79490fe48bc5fe2bb40f18289908/math/src/main/scala/breeze/linalg/Vector.scala#L986)

In the above example, due to Double rounding errors, the expression `((1.1 - 0.9) / 0.1)` returns `2.0000000000000004`. 

I believe `math.floor` should be used instead. Same issue with rangeF function.

**Comment by dlwh** [comment]
thanks for the catch! fixing now
