### ISSUE TITLE
Breeze 1.0, Scala 2.13.0 and breeze-viz plots - NoClassDef error

### ISSUE THREAD

**Issue by darrenjw** [scalanlp/breeze#757]
I might be doing something dumb, but I wonder if there is some library incompatibility associated with Breeze viz and Scala 2.13.

sbt

set libraryDependencies += "org.scalanlp" %% "breeze" % "1.0"
set libraryDependencies += "org.scalanlp" %% "breeze-natives" % "1.0"
set libraryDependencies += "org.scalanlp" %% "breeze-viz" % "1.0"
set scalaVersion := "2.13.0"
console

import breeze.plot._
val fig = Figure()
val p = fig.subplot(0)

Crashes for me with a noclassdef found, but with Scala 2.12.8 doesn't.
I'm running OpenJdk 8.

**Comment by robertjneal** [comment]
I have the same problem. I'm on Java 1.8.0_111.

**Comment by dlwh** [comment]
(Sorry for the slow response. it appears I stopped receiving github notifications.)

Will attempt to fix soon.

**Comment by Allowq** [comment]
@dlwh how long are you going to solve this issue?

**Comment by darrenjw** [comment]
Closing as seems to be fixed in 1.1.
