### ISSUE TITLE
Bug when Vector subset is assigned to itself?

### ISSUE THREAD

**Issue by bellaz89** [scalanlp/breeze#765]
When a subsect of a vector is assigned to itself it gives an incorrect result.
Example

```scala
val a = DenseVector(1,2,3,4)
a(1 to 3) := a(0 to 2)
// returns  a = DenseVector(1, 1, 1, 1)
// I would have expected a = DenseVector(1, 1, 2, 3) instead.
```

It seems that the code is not managing the sanity of copy operations when the destination memory is equal to the origin memory. In other libraries (eg. numpy) it works as intended. Probably the same happens for matrices...

**Comment by dlwh** [comment]
Yeah this is a case I missed. I thought I fixed these. I'll try to get to it soon

**Comment by dlwh** [comment]
(It appears I stopped receiving email notifications. Sorry about that!)

**Comment by dlwh** [comment]
this ended up being hilariously complicated to do "right". it's now a bit too conservative, but only a bit.
