### ISSUE TITLE
Auto boxing inside foreach DenseVector[Double] when call norm function

### ISSUE THREAD

**Issue by kovrizhin** [scalanlp/breeze#771]
When we call `norm` function for `DenseVector` we always have boxing/unboxing stuff.

I am not pro in scala but looks like it is because of foreach use generic approach: 
`override def foreach[@spec(Unit) U](fn: (V) => U)`

Also the second problem would be:
`val nn = f.sNorm(v); sum += nn * nn`
looks like here it will be also convert to java.lang.Double 

May be it is possible to simple rewrite it as normal for-loop and don't use implicit resolving sNorm function.

I spent a bit of time but not sure how to do it correctly and in generic way, and this is why I decide to  write here may be you can help.

Thanks in advance

**Comment by dlwh** [comment]
it does seem to be boxing. That's infuriating. I'll use a manual loop

**Comment by dlwh** [comment]
ok fixed in master

**Comment by kovrizhin** [comment]
Thanks a lot, for a quick fix. I have a look into changes, looks cool.

But I have 2  question:

1) 
DenseVectorOps also has some on method, which mostly calls and make a bigger problem:
`
  implicit def canNorm[T: Field]: norm.Impl[DenseVector[T], Double] = {
    val f = implicitly[Field[T]]
    new norm.Impl[DenseVector[T], Double] {
      override def apply(v: DenseVector[T]): Double = {
        import v._
        var sum = 0.0
        foreach(v => { val nn = f.sNorm(v); sum += nn * nn })
        math.sqrt(sum)
      }
    }
  }
`
2) 
Changes from  v.foreach -> to simple cforRange(0 until v.length) can be a bug, because foreach used
stride, offset, what do you think?
`
 override def foreach[@spec(Unit) U](fn: (V) => U): Unit = {
    if (stride == 1) { // ABCE stuff
      cforRange(offset until (offset + length)) { j =>
        fn(data(j))
      }
    } else {
      var i = offset
      cforRange(0 until length) { j =>
        fn(data(i))
        i += stride
      }
    }
  }
`

**Comment by dlwh** [comment]
(1)'s a good point and I'll have to fix.

(2) it's only an issue if you go through the data array. If you use apply on DenseVector (which I do in norm) it's handled there. It's a bit slower to not hit data directly, but it's more of a pain to write.
