### ISSUE TITLE
Should a trait be used instead of DenseMatrix / DenseVector?

### ISSUE THREAD

**Issue by aliakhtar** [scalanlp/breeze#775]
I find myself using the concrete classes DenseMatrix / DenseVector a lot. Is there a trait I should use instead so I can switch out the implementation to HashVector / SparseVector in future if needed?

I tried using VectorLike but it takes in a lot of type params.

**Comment by dlwh** [comment]
There's Vector and Matrix, but I don't recommend using them unless you're
pretty sure you're going to want the genericness. It slows things down.

**Comment by aliakhtar** [comment]
You mean slow performance wise? Or just slower to code?

**Comment by dlwh** [comment]
sorry missed this. slow in both senses.
