### ISSUE TITLE
Broken Scala 2.11 build

### ISSUE THREAD

**Issue by nightscape** [scalanlp/breeze#777]
Hi @dlwh,

the Scala 2.11 build seems to be broken due to the [usage of `ReusableBuilder` in `ArrayBuilder`](https://github.com/scalanlp/breeze/blob/master/math/src/main/scala_2.11_2.12/breeze/util/ArrayBuilder.scala#L27).
Is it worth fixing this, or should Scala 2.11 just be removed from Travis?
I could create a PR in both cases.

**Comment by dlwh** [comment]
eh, either way. Happy to drop 2.11. I was only committed to getting 1.0 out with all 3 versions.

**Comment by nightscape** [comment]
Are the Spark people in contact with you? Afaik they use Breeze in SparkML.
Spark wanting to maintain a 2.11 build would be the last reason to keep it in my opinion.

**Comment by dlwh** [comment]
Last I checked they still use it, but it's been a while.

I honestly haven't heard anything from Spark people in years.
