### ISSUE TITLE
vectorization and simd

### ISSUE THREAD

**Issue by schahaha** [scalanlp/breeze#787]
Can you use this library to achieve vectorized calculations?
If yes,  and Java and Scala do not have vectorized operators. How is this library implemented at the bottom?

**Comment by dlwh** [comment]
For dense vectors and matrices, Breeze relies on https://github.com/fommil/netlib-java . In particular, if you use the `breeze-natives` dependency, netlib-java will attempt to load your system's native BLAS, which is likely to be vectorized, especially if you follow the setup instructions in netlib-java.
