### ISSUE TITLE
No build for version 1.1 and scala 2.11 in maven central

### ISSUE THREAD

**Issue by bxacsq** [scalanlp/breeze#793]
The latest build for breeze is version 1.1 in maven central repo. But it seems there are only build for scala 2.12 and 2.13, no build for scala 2.11, is there any specific reason for that?

If not, could you please also publish the build for scala 2.11? 

Thanks,
Russell

**Comment by dlwh** [comment]
Yeah, I said my the release notes (on the mailing list) that basically I dropped it because it's annoying to maintain support for 3 versions of scala for a library like this.

If you really need it I can try to bring it back, but I'd rather push you to update to 2.12 or 2.13 if that's an option.
