### ISSUE TITLE
Misleading docs?

### ISSUE THREAD

**Issue by LLCampos** [scalanlp/breeze#815]
[Here](https://github.com/scalanlp/breeze/wiki/Quickstart#operators) it is written that "Elementwise multiplication" is done through `a :* b`. But this [doesn't seem to work](https://scastie.scala-lang.org/wgbrP5QvTgmQzVSQkEWiJg)?

```scala
import breeze.linalg._

val v1 = DenseVector(1.0, 2.0, 3.0)

 v1 :* 2
```

Scala 2.13.6, breeze 1.2

**Comment by darrenjw** [comment]
The operator has been renamed to avoid surprising precedence. So
```
v1 *:* 2.0
```
should do what you want. The docs do need updating accordingly.

**Comment by dlwh** [comment]
fixed the docs!
