### ISSUE TITLE
Compile Error when adding a constant to DenseVector/DenseMatrix

### ISSUE THREAD

**Issue by imperaton** [scalanlp/breeze#816]
The Following yields an error: (Scala 2.13, Breeze 1.2)
```
import breeze.linalg._

// Works Fine
1.0 - DenseVector(1.0, 2.0)
1.0 - DenseMatrix((1.0, 2.0), (3.0, 4.0))

// Error: 
// overloaded method + with alternatives: ... cannot be applied to (breeze.linalg.DenseVector[Double])
1.0 + DenseVector(1.0, 2.0)
1.0 + DenseMatrix((1.0, 2.0), (3.0, 4.0))
```

**Comment by dlwh** [comment]
Sorry I thought I replied to this. Scala's weird treatment of `+` to match Java's for string concatenation somehow makes it so that I can't make this overload work. You can use `+:+` instead if you want, or obviously you can just flip the LHS and RHS.
