### ISSUE TITLE
.toScalaVector() gives SeqOps error

### ISSUE THREAD

**Issue by Quafadas** [scalanlp/breeze#824]
https://scastie.scala-lang.org/Quafadas/8PLGVS6uTn214j14p1LgMQ

```
val dv = breeze.linalg.DenseVector[Int](1,2,3,4,5)
dv.toScalaVector()

missing argument for parameter i of method apply in trait SeqOps: (i: Int): Int
```
I get this with Breeze 2.0 and scala 3.1.0

**Comment by dlwh** [comment]
toScalaVector doesn't have an argument list so the compiler thinks you're
trying to invoke the apply method of the returned Vector. Just remove the
parentheses

**Comment by Quafadas** [comment]
Oh dear, that's embarrassing. THankyou for the quick reply.
