### ISSUE TITLE
WishartTest doesn't compile

### ISSUE THREAD

**Issue by SethTisue** [scalanlp/breeze#841]
on master, on Scala 2.13.8:

```
[error] /Users/tisue/breeze/math/src/test/scala/breeze/stats/distributions/WishartTest.scala:25:19: could not find implicit value for parameter impl: breeze.stats.mean.Impl[IndexedSeq[breeze.linalg.DenseMatrix[Double]],VR]
[error]       val m = mean(sample)
[error]                   ^
```

this came up in the Scala 2.13 community build, and I'm also able to reproduce it locally in a fresh checkout

I don't understand why #839 isn't showing the same failure?!

**Comment by SethTisue** [comment]
> I don't understand why https://github.com/scalanlp/breeze/pull/839 isn't showing the same failure?!

perhaps because `.github/workflows/scala.yml` does `sbt test` instead of `sbt +test`?

**Comment by dlwh** [comment]
Sorry! That's probably why. Will try to get to it this weekend

**Comment by SethTisue** [comment]
scala/community-build@8da9bde2 :+1:
