### ISSUE TITLE
Using the Project Panama SIMD APIs

### ISSUE THREAD

**Issue by alexklibisz** [scalanlp/breeze#851]
Hi, this is perhaps less of an issue and more of a discussion. I'm curious if there has been any interest (or any efforts) in leveraging the Project Panama Vector APIs in this project? https://openjdk.org/jeps/426

**Comment by dlwh** [comment]
Hi Alex, @luhenry's netlib (which Breeze uses for BLAS) should automatically [use the Vector APIs](https://github.com/luhenry/netlib/blob/6835050840ead1a724e2f305875c92d7cc21f834/blas/src/main/java/dev/ludovic/netlib/blas/VectorBLAS.java)

If there's something missing, I'd be happy to review a PR or (more likely) send it over to luhenry... Realistically I'm not going to do anything myself though.

**Comment by alexklibisz** [comment]
Good to know, thank you! It's documented here, in case anyone else stumbles upon this: https://github.com/luhenry/netlib#vector-based-acceleration-for-java-16

> Java 16 introduced the [Vector API](https://openjdk.java.net/jeps/338), a Java-based implementation providing access to hardware acceleration. [VectorBLAS](https://github.com/luhenry/netlib/blob/master/blas/src/main/java/dev/ludovic/netlib/blas/VectorBLAS.java) takes advantage of this API to implement most of the BLAS API.

> The performance is on-par or above the native libraries on most [Level-1](http://www.netlib.org/blas/#_level_1) and [Level-2](http://www.netlib.org/blas/#_level_2) BLAS subroutines. For [Level-3](http://www.netlib.org/blas/#_level_3) BLAS subroutines, the performance still doesn't match native libraries ([some thought on why](https://mail.openjdk.java.net/pipermail/panama-dev/2021-January/011930.html)).
